import { useCallback, useEffect, useMemo, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { supabase } from '@/lib/supabase';
import { safeErrorMessage } from '@/lib/safeError';
import type { OperationalTest } from './CatalogueMasterSections';

const structureCodes = ['ABG','ABS_DLC','ADA','APTT','BILE_ACID','BILIRUBIN_TD','BLOOD_GROUP_RH','BT_CT','COAG_PROFILE','DENGUE_IGM_IGG_PANEL','DENGUE_PANEL','DLC_3PART','DOUBLE_MARKER_MATERNAL_SCREEN_2_TESTS','GLUCOSE_TOLERANCE_TEST_GTT_PREGNANCY','GTT','HAV_PANEL','HIV_CARD_TEST','HPLC','IRON_PROFILE','LEUKEMIA_DLC','LUPUS_ANTICOAGULANT_DRVVT','MALARIA_ANTIGEN','MICROALBUMIN_CREATININE_RATIO_URINE_RANDOM','MICROALBUMIN_URINE_24_HOURS','MP_CARD_TEST','PLATELET_INDICES','PT_INR','RBC_INDICES','RUBELLA','SCRUB_TYPHUS','TB_GOLD_INTERFERON_GAMMA_RELEASE_ASSAY','TYPHIDOT_ANTIBODIES','WEIL_FELIX_TEST_SERUM'];
const optionCodes = ['ANTI_NUCLEAR_ANTIBODY_ANA_BY_ELISA','CEA_CARCINOEMBRYONIC_ANTIGEN','GCT','HAV_IGG','HAV_IGM','HAV_TOTAL_AB','KALA_AZAR','MP_MICROSCOPIC','THYROGLOBULIN_ANTIBODY_TGAB','TPHA','TROPONIN_I_RAPID','UPT','URINE_FOR_ELISA_PREGNANCY'];
const priceCodes = ['PANEL_CBC_WITH_ABSOLUTE_COUNTS','PANEL_KFT_WITHOUT_EGFR','PANEL_ELECTROLYTES_PANEL','PANEL_ARTHRITIS_PROFILE','PANEL_PROTEIN_FRACTION','PANEL_TORCH_PROFILE','PANEL_AMH_PANEL','PANEL_VIRAL_MARKER','PANEL_PCOD_PANEL','PANEL_CBC_WITH_MORPHOLOGY'];

type OptionSet={id:string;code:string;name:string;catalogue_option_values?:Array<{label:string;display_order:number}>};
type PriceRow={id:string;code:string;name:string;panel_id:string;test_categories?:{name:string}|null;catalogue_rate_versions?:Array<{status:string;price_paisa:number|null}>;catalogue_panels?:{catalogue_panel_ratelist_links?:Array<{ratelist_name:string}>}|null};

export function CatalogueCompletionQueue({tests,canConfigure,canManage,onConfigure}:{tests:OperationalTest[];canConfigure:boolean;canManage:boolean;onConfigure:(test:OperationalTest)=>void}) {
  const [optionSets,setOptionSets]=useState<OptionSet[]>([]); const [prices,setPrices]=useState<PriceRow[]>([]);
  const [error,setError]=useState(''); const [message,setMessage]=useState(''); const [choice,setChoice]=useState<Record<string,string>>({});
  const [customOpen,setCustomOpen]=useState(false); const [customCode,setCustomCode]=useState(''); const [customName,setCustomName]=useState(''); const [customValues,setCustomValues]=useState('');
  const [priceItem,setPriceItem]=useState<PriceRow|null>(null); const [amount,setAmount]=useState(''); const [effective,setEffective]=useState(new Date().toISOString().slice(0,10));
  const load=useCallback(async()=>{setError('');const [optionResult,priceResult]=await Promise.all([
    supabase.from('catalogue_option_sets').select('id,code,name,catalogue_option_values(label,display_order)').eq('lifecycle_status','Active').order('name'),
    supabase.from('catalogue_panel_services').select('id,code,name,panel_id,test_categories:category_id(name),catalogue_rate_versions(status,price_paisa),catalogue_panels:panel_id(catalogue_panel_ratelist_links(ratelist_name))').in('code',priceCodes).order('name'),
  ]);const failed=optionResult.error||priceResult.error;if(failed){setError(safeErrorMessage(failed,'Catalogue completion queue could not be loaded.'));return;}setOptionSets((optionResult.data||[]) as unknown as OptionSet[]);setPrices((priceResult.data||[]) as unknown as PriceRow[]);},[]);
  useEffect(()=>{void load();},[load,tests]);
  const structurallyValid=(test:OperationalTest)=>{const active=(test.parameters||[]).filter(parameter=>parameter.is_active!==false&&parameter.lifecycle_status!=='Archived'&&parameter.value_type!=='Heading');return active.length>0&&active.every(parameter=>Boolean(parameter.name.trim()&&parameter.code.trim()&&parameter.value_type)&&(!['Select','Boolean'].includes(parameter.value_type||'')||Boolean(parameter.option_set_id)));};
  const structures=useMemo(()=>tests.filter(test=>structureCodes.includes(test.code)&&!structurallyValid(test)),[tests]);
  const qualitative=useMemo(()=>tests.filter(test=>optionCodes.includes(test.code)&&!structurallyValid(test)),[tests]);
  const missingPrices=useMemo(()=>prices.filter(item=>!(item.catalogue_rate_versions||[]).some(rate=>rate.status==='Active'&&rate.price_paisa!=null)),[prices]);
  const assign=async(test:OperationalTest)=>{const optionSetId=choice[test.id];const parameter=(test.parameters||[]).find(p=>p.is_active!==false&&['Select','Boolean'].includes(p.value_type||''));if(!optionSetId||!parameter){setError('Select an approved option set. The test must have an active Select or Boolean parameter.');return;}const detail=await supabase.from('parameters').select('row_version').eq('id',parameter.id).single();if(detail.error){setError(safeErrorMessage(detail.error,'Parameter could not be refreshed.'));return;}const result=await supabase.rpc('catalogue_set_parameter_option_set',{p_parameter_id:parameter.id,p_option_set_id:optionSetId,p_expected_version:detail.data.row_version});if(result.error){setError(safeErrorMessage(result.error,'Option set could not be assigned.'));return;}setMessage(`${test.name} is now linked to the selected approved result vocabulary.`);await load();};
  const createCustom=async()=>{const values=customValues.split('\n').map(v=>v.trim()).filter(Boolean);if(!customCode.trim()||!customName.trim()||values.length<2){setError('Custom vocabulary requires a code, name, and at least two option labels.');return;}const setResult=await supabase.rpc('catalogue_save_option_set',{p_payload:{code:customCode.trim().toUpperCase(),name:customName.trim()},p_expected_version:null});if(setResult.error){setError(safeErrorMessage(setResult.error,'Custom option set could not be created.'));return;}for(let index=0;index<values.length;index++){const label=values[index];const valueResult=await supabase.rpc('catalogue_save_option_value',{p_payload:{option_set_id:setResult.data,value_code:label.toUpperCase().replace(/[^A-Z0-9]+/g,'_'),label,display_order:index+1},p_expected_version:null});if(valueResult.error){setError(safeErrorMessage(valueResult.error,'An option value could not be saved.'));return;}}setCustomOpen(false);setCustomCode('');setCustomName('');setCustomValues('');setMessage('Custom option set created. Select it for the appropriate qualitative test.');await load();};
  const savePrice=async()=>{if(!priceItem)return;const pricePaisa=Math.round(Number(amount)*100);if(!Number.isFinite(pricePaisa)||pricePaisa<0){setError('Enter a valid non-negative NPR amount.');return;}const created=await supabase.rpc('catalogue_create_rate_version',{p_entity_type:'Panel',p_entity_id:priceItem.id,p_other_service_code:null,p_price_paisa:pricePaisa,p_effective_from:new Date(`${effective}T00:00:00+05:45`).toISOString()});if(created.error){setError(safeErrorMessage(created.error,'Price version could not be created.'));return;}const activated=await supabase.rpc('catalogue_activate_rate',{p_rate_id:created.data,p_expected_version:1});if(activated.error){setError(safeErrorMessage(activated.error,'Price version was created but could not be activated.'));return;}setMessage(`${priceItem.name} now has an active future-billing rate. Historical bill prices are unchanged.`);setPriceItem(null);setAmount('');await load();};
  return <Stack spacing={2} sx={{mb:2}}>
    <Card><CardContent><Typography variant="h6" fontWeight={800}>Catalogue Completion</Typography><Typography variant="body2" color="text.secondary" sx={{mb:2}}>Only current operator actions are shown. Completed items disappear after server readiness is recalculated.</Typography><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:2}}><Alert severity={structures.length?'warning':'success'}>Result structures remaining: <strong>{structures.length}</strong></Alert><Alert severity={qualitative.length?'warning':'success'}>Qualitative selections remaining: <strong>{qualitative.length}</strong></Alert><Alert severity={missingPrices.length?'warning':'success'}>Prices remaining: <strong>{missingPrices.length}</strong></Alert></Box></CardContent></Card>
    {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}{message&&<Alert severity="success" onClose={()=>setMessage('')}>{message}</Alert>}
    <Card><CardContent><Typography variant="h6" fontWeight={800}>Configure Result Structure</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1}}>Add ordered parameters, result types, units, precision, option sets, ranges, methods, instruments and report visibility. Method and instrument are optional for basic structural readiness.</Typography><Table size="small"><TableHead><TableRow><TableCell>Test</TableCell><TableCell>Current structure</TableCell><TableCell>Action</TableCell></TableRow></TableHead><TableBody>{structures.map(test=><TableRow key={test.id}><TableCell><Typography fontWeight={700}>{test.name}</Typography><Typography variant="caption">{test.code}</Typography></TableCell><TableCell>Result Structure Incomplete</TableCell><TableCell><Button disabled={!canConfigure} onClick={()=>onConfigure(test)}>Configure Result Structure</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Card><CardContent><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}}><Box><Typography variant="h6" fontWeight={800}>Qualitative Result Options</Typography><Typography variant="body2" color="text.secondary">No vocabulary is preselected. Choose an approved set and readiness recalculates immediately.</Typography></Box>{canConfigure&&<Button onClick={()=>setCustomOpen(true)}>Create custom option set</Button>}</Stack><Table size="small"><TableHead><TableRow><TableCell>Test</TableCell><TableCell>Existing configuration</TableCell><TableCell>Approved option set</TableCell><TableCell>Action</TableCell></TableRow></TableHead><TableBody>{qualitative.map(test=><TableRow key={test.id}><TableCell><Typography fontWeight={700}>{test.name}</Typography><Typography variant="caption">{test.code}</Typography></TableCell><TableCell>{(test.parameters||[]).filter(p=>p.is_active!==false).map(p=>`${p.name} · ${p.value_type}`).join(', ')||'Select/Boolean parameter not present'}</TableCell><TableCell><TextField select size="small" label="Choose option set" value={choice[test.id]||''} onChange={e=>setChoice({...choice,[test.id]:e.target.value})} sx={{minWidth:240}}><MenuItem value=""><em>No selection</em></MenuItem>{optionSets.map(set=><MenuItem key={set.id} value={set.id}>{set.name}</MenuItem>)}</TextField></TableCell><TableCell><Button disabled={!canConfigure||!choice[test.id]} onClick={()=>void assign(test)}>Apply</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Card><CardContent><Typography variant="h6" fontWeight={800}>Missing Prices</Typography><Typography variant="body2" color="text.secondary" sx={{mb:1}}>Super Admin only. Unpriced services cannot create a bill; activation affects future billing only.</Typography><Table size="small"><TableHead><TableRow><TableCell>Panel</TableCell><TableCell>Code</TableCell><TableCell>Category</TableCell><TableCell>Ratelist/package linkage</TableCell><TableCell>Current price</TableCell><TableCell>Action</TableCell></TableRow></TableHead><TableBody>{missingPrices.map(item=><TableRow key={item.id}><TableCell>{item.name}</TableCell><TableCell>{item.code}</TableCell><TableCell>{item.test_categories?.name||'Not specified'}</TableCell><TableCell>{item.catalogue_panels?.catalogue_panel_ratelist_links?.map(link=>link.ratelist_name).join(', ')||'Not specified'}</TableCell><TableCell>Not specified</TableCell><TableCell><Button disabled={!canManage} onClick={()=>setPriceItem(item)}>Add Price</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Dialog open={customOpen} onClose={()=>setCustomOpen(false)} maxWidth="sm" fullWidth><DialogTitle>Create custom qualitative option set</DialogTitle><DialogContent dividers><Stack spacing={2}><TextField label="Option-set code" value={customCode} onChange={e=>setCustomCode(e.target.value)}/><TextField label="Display name" value={customName} onChange={e=>setCustomName(e.target.value)}/><TextField multiline minRows={4} label="Options — one label per line" value={customValues} onChange={e=>setCustomValues(e.target.value)}/><Alert severity="info">Creating a vocabulary does not assign it automatically. Select it explicitly for the appropriate test.</Alert></Stack></DialogContent><DialogActions><Button onClick={()=>setCustomOpen(false)}>Cancel</Button><Button variant="contained" onClick={()=>void createCustom()}>Save option set</Button></DialogActions></Dialog>
    <Dialog open={Boolean(priceItem)} onClose={()=>setPriceItem(null)} maxWidth="xs" fullWidth><DialogTitle>Add Price — {priceItem?.name}</DialogTitle><DialogContent dividers><Stack spacing={2}><TextField label="NPR amount" type="number" value={amount} onChange={e=>setAmount(e.target.value)} inputProps={{min:0,step:.01}}/><TextField label="Effective date" type="date" value={effective} onChange={e=>setEffective(e.target.value)} InputLabelProps={{shrink:true}}/><Divider/><Typography variant="body2">Activation applies to future bills. Historical price snapshots remain immutable.</Typography></Stack></DialogContent><DialogActions><Button onClick={()=>setPriceItem(null)}>Cancel</Button><Button variant="contained" disabled={!canManage||!amount.trim()} onClick={()=>void savePrice()}>Save and Activate</Button></DialogActions></Dialog>
  </Stack>;
}
