import { useCallback, useEffect, useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Select, Table, TableBody, TableCell, TableContainer, TableHead, TablePagination, TableRow, TextField, Typography } from '@mui/material';
import { supabase } from '@/lib/supabase';
import { safeErrorMessage } from '@/lib/safeError';
import { formatAdDate } from '@/lib/dateTime';
import { formatPaisa, parseRupeesToPaisa } from '@/lib/currency';

type EntityType='Test'|'Panel'|'Package';
type RateRow={entity_id:string;entity_type:EntityType;code:string;name:string;category_id?:string|null;category:string;entity_status:'Draft'|'Active'|'Archived';rate_id?:string|null;price_paisa?:number|null;effective_from?:string|null;rate_status?:string|null;rate_row_version?:number|null;updated_at?:string|null};
type HistoryRow={id:string;version_number:number;price_paisa:number|null;effective_from:string|null;status:string;row_version:number;used_by_bill_count:number};
type Category={id:string;name:string};

export function CataloguePriceMasterSection({canManage}:{canManage:boolean}){
 const [rows,setRows]=useState<RateRow[]>([]),[categories,setCategories]=useState<Category[]>([]),[total,setTotal]=useState(0);
 const [error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 const [query,setQuery]=useState(''),[category,setCategory]=useState(''),[lifecycle,setLifecycle]=useState(''),[priced,setPriced]=useState(''),[entityType,setEntityType]=useState('');
 const [sort,setSort]=useState('name'),[descending,setDescending]=useState(false),[page,setPage]=useState(0),[pageSize,setPageSize]=useState(25);
 const [selected,setSelected]=useState<RateRow|null>(null),[price,setPrice]=useState(''),[reason,setReason]=useState('');
 const [historyFor,setHistoryFor]=useState<RateRow|null>(null),[history,setHistory]=useState<HistoryRow[]>([]);
 const entityArgs=(row:RateRow)=>({p_entity_type:row.entity_type,p_entity_id:row.entity_id,p_other_service_code:null});
 const load=useCallback(async()=>{setLoading(true);setError('');const result=await supabase.rpc('catalogue_search_rate_list',{p_query:query.trim()||null,p_category_id:category||null,p_lifecycle:lifecycle||null,p_priced:priced===''?null:priced==='priced',p_entity_type:entityType||null,p_sort:sort,p_desc:descending,p_offset:page*pageSize,p_limit:pageSize});setLoading(false);if(result.error){setError(safeErrorMessage(result.error,'Rate list could not be loaded.'));return;}const data=(result.data||[]) as Array<{item:RateRow;total_count:number}>;setRows(data.map(x=>x.item));setTotal(Number(data[0]?.total_count||0));},[query,category,lifecycle,priced,entityType,sort,descending,page,pageSize]);
 useEffect(()=>{void supabase.from('test_categories').select('id,name').order('display_order').then(result=>{if(!result.error)setCategories((result.data||[]) as Category[])})},[]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[load]);
 const save=async()=>{if(!selected)return;const paisa=parseRupeesToPaisa(price);if(paisa===null||paisa<=0){setError('Enter a positive NPR rate with no more than two decimal places.');return;}if(!reason.trim()){setError('A rate-change reason is required.');return;}setError('');const result=await supabase.rpc('catalogue_set_current_rate',{p_entity_type:selected.entity_type,p_entity_id:selected.entity_id,p_price_paisa:paisa,p_expected_rate_id:selected.rate_id||null,p_expected_rate_version:selected.rate_row_version||null,p_reason:reason.trim()});if(result.error){setError(safeErrorMessage(result.error,'Rate was not changed. Refresh if another administrator updated it.'));return;}setMessage(`Rate updated to ${formatPaisa(paisa)}. Existing bills and orders were not changed.`);setSelected(null);setPrice('');setReason('');await load()};
 const openHistory=async(row:RateRow)=>{setHistoryFor(row);const result=await supabase.rpc('catalogue_rate_history',entityArgs(row));if(result.error)setError(safeErrorMessage(result.error));else setHistory(((result.data||[]) as Array<{item:HistoryRow}>).map(x=>x.item))};
 const removeRate=async(rate:HistoryRow)=>{const result=await supabase.rpc('catalogue_delete_or_archive_rate',{p_rate_id:rate.id,p_expected_version:rate.row_version});if(result.error){setError(safeErrorMessage(result.error));return;}setMessage(result.data==='Deleted'?'Unused draft rate deleted.':'Rate archived; historical billing remains unchanged.');if(historyFor)await openHistory(historyFor);await load()};
 const reset=()=>setPage(0);
 return <Card><CardContent><Typography variant="h6" fontWeight={800}>Rate List</Typography><Typography variant="body2" color="text.secondary" sx={{mb:2}}>Current production prices for tests, panels and packages. Values are committed as integer paisa; saved bill snapshots never change.</Typography>
 {error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}{message&&<Alert severity="success" sx={{mb:2}} onClose={()=>setMessage('')}>{message}</Alert>}
 <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'2fr repeat(5,1fr)'},gap:1.5,mb:2}}>
  <TextField size="small" label="Search code or name" value={query} onChange={e=>{setQuery(e.target.value);reset()}}/>
  <FormControl size="small"><InputLabel>Category</InputLabel><Select label="Category" value={category} onChange={e=>{setCategory(e.target.value);reset()}}><MenuItem value="">All</MenuItem>{categories.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl>
  <FormControl size="small"><InputLabel>Status</InputLabel><Select label="Status" value={lifecycle} onChange={e=>{setLifecycle(e.target.value);reset()}}><MenuItem value="">All</MenuItem><MenuItem value="Active">Active</MenuItem><MenuItem value="Draft">Inactive / Draft</MenuItem><MenuItem value="Archived">Archived</MenuItem></Select></FormControl>
  <FormControl size="small"><InputLabel>Pricing</InputLabel><Select label="Pricing" value={priced} onChange={e=>{setPriced(e.target.value);reset()}}><MenuItem value="">All</MenuItem><MenuItem value="priced">Priced</MenuItem><MenuItem value="unpriced">Unpriced</MenuItem></Select></FormControl>
  <FormControl size="small"><InputLabel>Type</InputLabel><Select label="Type" value={entityType} onChange={e=>{setEntityType(e.target.value);reset()}}><MenuItem value="">All</MenuItem><MenuItem value="Test">Tests</MenuItem><MenuItem value="Panel">Panels</MenuItem><MenuItem value="Package">Packages</MenuItem></Select></FormControl>
  <FormControl size="small"><InputLabel>Sort</InputLabel><Select label="Sort" value={`${sort}:${descending?'desc':'asc'}`} onChange={e=>{const [s,d]=e.target.value.split(':');setSort(s);setDescending(d==='desc');reset()}}><MenuItem value="name:asc">Name A–Z</MenuItem><MenuItem value="name:desc">Name Z–A</MenuItem><MenuItem value="code:asc">Code A–Z</MenuItem><MenuItem value="rate:asc">Rate low–high</MenuItem><MenuItem value="rate:desc">Rate high–low</MenuItem><MenuItem value="updated_at:desc">Recently updated</MenuItem></Select></FormControl>
 </Box>
 <TableContainer><Table size="small"><TableHead><TableRow><TableCell>Test Code</TableCell><TableCell>Test Name</TableCell><TableCell>Category</TableCell><TableCell>Current Rate</TableCell><TableCell>Status</TableCell><TableCell>Last Updated</TableCell><TableCell align="right">Update action</TableCell></TableRow></TableHead><TableBody>{!loading&&rows.length===0&&<TableRow><TableCell colSpan={7} align="center">No matching catalogue services.</TableCell></TableRow>}{rows.map(row=><TableRow key={`${row.entity_type}-${row.entity_id}`} hover><TableCell>{row.code}<Typography variant="caption" display="block" color="text.secondary">{row.entity_type}</Typography></TableCell><TableCell>{row.name}</TableCell><TableCell>{row.category||'Unassigned'}</TableCell><TableCell>{row.rate_status==='Active'&&row.price_paisa!=null?formatPaisa(row.price_paisa):<Typography color="warning.main">Configuration required</Typography>}</TableCell><TableCell>{row.entity_status}{row.rate_status?` · ${row.rate_status}`:''}</TableCell><TableCell>{row.updated_at?formatAdDate(row.updated_at):'—'}</TableCell><TableCell align="right"><Button size="small" onClick={()=>void openHistory(row)}>History</Button>{canManage&&<Button size="small" onClick={()=>{setSelected(row);setPrice(row.price_paisa==null?'':(row.price_paisa/100).toFixed(2));setReason('')}}>{row.rate_status==='Active'?'Update Rate':'Configure Rate'}</Button>}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
 <TablePagination component="div" count={total} page={page} rowsPerPage={pageSize} rowsPerPageOptions={[10,25,50,100]} onPageChange={(_,next)=>setPage(next)} onRowsPerPageChange={e=>{setPageSize(Number(e.target.value));setPage(0)}}/>
 </CardContent>
 <Dialog open={Boolean(selected)} onClose={()=>setSelected(null)} maxWidth="xs" fullWidth><DialogTitle>{selected?.name}</DialogTitle><DialogContent dividers><Alert severity="info" sx={{mb:2}}>This rate applies only to new bills. The update is atomic and audited.</Alert><TextField fullWidth label="Rate (NPR)" value={price} onChange={e=>setPrice(e.target.value)} inputProps={{inputMode:'decimal'}} sx={{mb:2}}/><TextField fullWidth required label="Reason for change" value={reason} onChange={e=>setReason(e.target.value)} multiline minRows={2}/></DialogContent><DialogActions><Button onClick={()=>setSelected(null)}>Cancel</Button><Button variant="contained" onClick={()=>void save()}>Review and commit rate</Button></DialogActions></Dialog>
 <Dialog open={Boolean(historyFor)} onClose={()=>setHistoryFor(null)} maxWidth="md" fullWidth><DialogTitle>Rate History · {historyFor?.name}</DialogTitle><DialogContent dividers><Table size="small"><TableHead><TableRow><TableCell>Version</TableCell><TableCell>Rate</TableCell><TableCell>Effective From</TableCell><TableCell>Status</TableCell><TableCell>Historical Bills</TableCell><TableCell align="right">Action</TableCell></TableRow></TableHead><TableBody>{history.map(rate=><TableRow key={rate.id}><TableCell>{rate.version_number}</TableCell><TableCell>{rate.price_paisa==null?'Not configured':formatPaisa(rate.price_paisa)}</TableCell><TableCell>{rate.effective_from?formatAdDate(rate.effective_from):'—'}</TableCell><TableCell>{rate.status}</TableCell><TableCell>{rate.used_by_bill_count}</TableCell><TableCell align="right">{canManage&&rate.status!=='Active'&&<Button size="small" color="warning" onClick={()=>void removeRate(rate)}>{rate.status==='Draft'&&rate.used_by_bill_count===0?'Delete Draft':'Archive'}</Button>}</TableCell></TableRow>)}</TableBody></Table></DialogContent><DialogActions><Button onClick={()=>setHistoryFor(null)}>Close</Button></DialogActions></Dialog>
 </Card>;
}
