import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControl,Grid,InputLabel,MenuItem,Select,Tab,Tabs,TextField,Typography} from '@mui/material';
import PrintIcon from '@mui/icons-material/Print'; import DownloadIcon from '@mui/icons-material/Download';
import {supabase} from '@/lib/supabase'; import {useAuth} from '@/hooks/useAuth'; import {usePermissions} from '@/hooks/usePermissions'; import {PERMISSION_KEYS} from '@/types/permissions';
import {formatDualDate,getNepalCurrentMonthKey,getNepalMonthBoundsFromKey,getNepalTodayAd} from '@/lib/dateTime';
import {AGE_GROUPS,CAPACITY_ROWS,CLIENT_METRICS,CONDITIONS,defaultHmisConfig,HmisConfig,HmisIdentitySnapshot,HmisSnapshot,OPD_ROWS,REFERRAL_SITES,SERVICES,SERVICE_SITES,csvSummary} from './hmisModel';
import {downloadBlob,printHmis} from './hmisPrint';
import {safeErrorMessage} from '@/lib/safeError';

type ReportRow={id:string;report_month:string;fiscal_year:string;reference_no:string|null;status:'Draft'|'Finalized'|'Submitted';current_version:number;finalized_at:string|null;submitted_at:string|null};
const emptyManual=()=>({clients:Object.fromEntries(AGE_GROUPS.map(a=>[a,Object.fromEntries(CLIENT_METRICS.map(m=>[m,{Female:'',Male:''}]))])),conditions:Object.fromEntries(CONDITIONS.map(x=>[x,{Female:'',Male:''}])),opd:Object.fromEntries(OPD_ROWS.map(x=>[x,{planned:'',conducted:''}])),referrals:{Female:'',Male:'',referredIn:'',referredOut:'',inPatient:'',emergency:''},capacity:Object.fromEntries(CAPACITY_ROWS.map(x=>[x,''])),mss:{date:'',implementation:'First',score:''},prepared:{name:'',designation:'',date:'',signature:''},verified:{name:'',designation:''},approved:{name:'',designation:''}});
const CellInput=({value,onChange,disabled=false,label}:{value:unknown;onChange:(v:string)=>void;disabled?:boolean;label:string})=><input aria-label={label} inputMode="numeric" disabled={disabled} value={String(value??'')} onChange={e=>onChange(e.target.value.replace(/[^0-9]/g,''))} style={{width:46,border:0,textAlign:'center',background:disabled?'#eee':'white'}}/>;
const Source=({children}:{children:React.ReactNode})=><small className="source-tag">{children}</small>;

export const HmisMonthlyReportPage:React.FC=()=>{
 const {user,profile}=useAuth(); const {can}=usePermissions(); const [tab,setTab]=useState(0); const [month,setMonth]=useState(getNepalCurrentMonthKey()); const [config,setConfig]=useState<HmisConfig>(defaultHmisConfig()); const [manual,setManual]=useState<any>(emptyManual()); const [identities,setIdentities]=useState<HmisIdentitySnapshot[]>([]); const [selected,setSelected]=useState({prepared:'',verified:'',approved:''}); const [auto,setAuto]=useState<any>({}); const [report,setReport]=useState<ReportRow|null>(null); const [history,setHistory]=useState<ReportRow[]>([]); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [revisionReason,setRevisionReason]=useState(''); const [submitOpen,setSubmitOpen]=useState(false); const [submission,setSubmission]=useState({date:getNepalTodayAd(),to:'',method:'Physical',reference:'',remarks:''}); const sheet=useRef<HTMLDivElement>(null);
 const editable=can(PERMISSION_KEYS.CAN_EDIT_HMIS_REPORTS)&&(!report||report.status==='Draft'); const canFinalize=can(PERMISSION_KEYS.CAN_FINALIZE_HMIS_REPORTS);
 const update=(path:string[],value:string)=>setManual((old:any)=>{const n=structuredClone(old);let p=n;for(const k of path.slice(0,-1))p=p[k];p[path.at(-1)!]=value;return n});
 const load=async()=>{setBusy(true);setMessage('');try{const monthDate=`${month}-01`;const responses=await Promise.all([supabase.from('hmis_facility_configuration').select('configuration').eq('facility_key','primary').maybeSingle(),supabase.from('hmis_monthly_reports').select('*').eq('report_month',monthDate).maybeSingle(),supabase.rpc('hmis_auto_summary',{p_month:monthDate}),supabase.from('hmis_monthly_reports').select('*').order('report_month',{ascending:false}),supabase.rpc('hmis_identity_options')]);const failure=responses.find(response=>response.error)?.error;if(failure)throw failure;const [{data:c},{data:r},{data:a},{data:h},{data:i}]=responses;if(c?.configuration)setConfig({...defaultHmisConfig(),...c.configuration} as HmisConfig);setIdentities((i??[]) as HmisIdentitySnapshot[]);setAuto(a??{});setReport(r as ReportRow|null);setHistory((h??[]) as ReportRow[]);if(r){const {data:m,error:manualError}=await supabase.from('hmis_monthly_manual_values').select('values_json').eq('report_id',r.id).maybeSingle();if(manualError)throw manualError;const values=m?.values_json??emptyManual();setManual(values);setSelected(values.identitySelections??{prepared:'',verified:'',approved:''})}else{setManual(emptyManual());setSelected({prepared:'',verified:'',approved:''})}}catch(e){setMessage(safeErrorMessage(e,'Unable to load HMIS report'))}finally{setBusy(false)}};
 // Month is the intentional reload boundary; draft edits must not trigger refetches.
 // oxlint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{void load()},[month]);
 const header=useMemo(()=>{const y=Number(month.slice(0,4)),m=Number(month.slice(5));const fy=m>=7?`${y}/${String(y+1).slice(-2)}`:`${y-1}/${String(y).slice(-2)}`;return{title:'Health Management Information System',formTitle:'Non-Public Health Facility Monthly Reporting Form',fiscalYear:fy,facilityName:config.facilityName,hfCode:config.hfCode,province:config.province,district:config.district,municipality:config.municipality,ward:config.ward,reportMonth:getNepalMonthBoundsFromKey(month).label,referenceNo:report?.reference_no??`${config.referencePrefix}-${month}`,subject:'Submission of Monthly Report on Hospital Services'}},[month,config,report]);
 const identity=(key:string)=>identities.find(x=>`${x.source}:${x.id}`===key)??null; const prepared=identity(selected.prepared)??{source:'Staff' as const,id:'',name:'',designation:'',signatureUrl:null};
 const snapshot:HmisSnapshot={header,auto,manual:{...manual,identitySelections:selected},identities:{prepared,verified:identity(selected.verified),approved:identity(selected.approved)},configured:config,provenance:{registeredPatients:'Auto from LIS',newClientsByAgeSex:'Auto from LIS',manual:'Manual HMIS Entry',facility:'Configured Facility Data'}};
 const saveDraft=async()=>{if(!user)return;setBusy(true);try{let id=report?.id;if(!id){const {data,error}=await supabase.from('hmis_monthly_reports').insert({report_month:`${month}-01`,fiscal_year:header.fiscalYear,reference_no:header.referenceNo,created_by:user.id}).select().single();if(error)throw error;id=data.id}const {error}=await supabase.from('hmis_monthly_manual_values').upsert({report_id:id,values_json:{...manual,identitySelections:selected},updated_by:user.id});if(error)throw error;setMessage('Draft saved with manual-value audit metadata.');await load()}catch(e){setMessage(safeErrorMessage(e,'HMIS draft could not be saved. Check the entries and try again.'))}finally{setBusy(false)}};
 const saveConfig=async()=>{if(!user)return;const {error}=await supabase.from('hmis_facility_configuration').upsert({facility_key:'primary',configuration:config,updated_by:user.id},{onConflict:'facility_key'});setMessage(error?safeErrorMessage(error,'HMIS facility configuration could not be saved.'):'Facility configuration saved. Explicit availability choices will be used in future reports.')};
 const finalize=async()=>{if(!report){setMessage('Save the draft before finalizing.');return}const {error}=await supabase.rpc('finalize_hmis_report',{p_report_id:report.id,p_snapshot:snapshot,p_revision_reason:report.current_version?revisionReason:null});setMessage(error?safeErrorMessage(error,'HMIS report could not be finalized. Check the required fields and try again.'):`Immutable version ${report.current_version+1} finalized.`);if(!error){setRevisionReason('');await load()}};
 const submit=async()=>{if(!report)return;const {error}=await supabase.rpc('record_hmis_submission',{p_report_id:report.id,p_submission_date:submission.date,p_submitted_to:submission.to,p_method:submission.method,p_reference:submission.reference||null,p_remarks:submission.remarks||null,p_attachment_path:null});setMessage(error?safeErrorMessage(error,'HMIS submission could not be recorded. Check the submission details and try again.'):'Submission event recorded.');if(!error){setSubmitOpen(false);await load()}};
 const exportCsv=()=>downloadBlob(csvSummary(snapshot),'text/csv;charset=utf-8',`HMIS-${month}.csv`);
 return <Box><Typography variant="h4" fontWeight={800}>HMIS Monthly Report</Typography><Typography color="text.secondary">HMIS 9.5-style non-public facility reporting · Nepal time · aggregate data only</Typography>{message&&<Alert sx={{my:2}} severity={message.toLowerCase().includes('failed')?'error':'info'}>{message}</Alert>}<Tabs value={tab} onChange={(_,v)=>setTab(v)}><Tab label="Monthly Form"/><Tab label="History"/><Tab label="Configuration"/></Tabs>
 {tab===0&&<><Box className="no-print" sx={{display:'flex',gap:1,my:2,flexWrap:'wrap'}}><TextField type="month" size="small" label="Report month" value={month} onChange={e=>setMonth(e.target.value)}/><Button disabled={!editable||busy} variant="contained" onClick={saveDraft}>Save Draft</Button><Button disabled={!canFinalize||!report||busy} onClick={finalize}>{report?.current_version?'Create Revision':'Finalize'}</Button>{Boolean(report?.current_version)&&<TextField size="small" label="Revision reason (required)" value={revisionReason} onChange={e=>setRevisionReason(e.target.value)}/>}<Button disabled={!canFinalize||!report?.current_version} onClick={()=>setSubmitOpen(true)}>Record Submission</Button><Button startIcon={<PrintIcon/>} onClick={()=>sheet.current&&printHmis(sheet.current,snapshot)}>Preview / Print / Save PDF</Button><Button startIcon={<DownloadIcon/>} onClick={exportCsv}>CSV Summary</Button></Box>
 <Card className="no-print" variant="outlined" sx={{mb:1}}><CardContent><Typography fontWeight={700}>Manual monthly details</Typography><Grid container spacing={1}>{[['mss','date','MSS Date','date'],['mss','score','MSS Score (%)','number'],['prepared','date','Prepared Date','date']].map(([section,key,label,type])=><Grid item xs={12} sm={3} key={label}><TextField fullWidth size="small" type={type} label={label} disabled={!editable} value={manual[section][key]} onChange={e=>update([section,key],e.target.value)} InputLabelProps={type==='date'?{shrink:true}:undefined}/></Grid>)}<Grid item xs={12} sm={3}><FormControl fullWidth size="small"><InputLabel>MSS Implementation</InputLabel><Select label="MSS Implementation" disabled={!editable} value={manual.mss.implementation} onChange={e=>update(['mss','implementation'],e.target.value)}><MenuItem value="First">First</MenuItem><MenuItem value="Second">Second</MenuItem></Select></FormControl></Grid>{(['prepared','verified','approved'] as const).map(role=><Grid item xs={12} sm={4} key={role}><FormControl fullWidth size="small"><InputLabel>{role[0].toUpperCase()+role.slice(1)} By{role==='prepared'?'':' (optional)'}</InputLabel><Select label={`${role} By`} disabled={!editable} value={selected[role]} onChange={e=>setSelected({...selected,[role]:e.target.value})}><MenuItem value=""><em>Not selected</em></MenuItem>{identities.map(x=><MenuItem key={`${x.source}:${x.id}`} value={`${x.source}:${x.id}`}>{x.name} — {x.designation} ({x.source})</MenuItem>)}</Select></FormControl></Grid>)}</Grid><Alert severity="info" sx={{mt:1}}>Each role is selected explicitly. Identities are never copied between roles; signatures/designations come only from the selected source record and are frozen in finalized versions.</Alert></CardContent></Card>
 <div ref={sheet} className="hmis-sheet"><Card variant="outlined"><CardContent sx={{p:1.5}}><Typography align="center" fontWeight={800}>{header.title}</Typography><Typography align="center" fontWeight={800}>{header.formTitle}</Typography><table><tbody><tr><td>Fiscal Year: {header.fiscalYear}</td><td colSpan={2}>Hospital / Facility Name: {header.facilityName||'—'}</td><td>HF Code: {header.hfCode||'—'}</td></tr><tr><td>Province: {header.province||'—'}</td><td>District: {header.district||'—'}</td><td>Municipality: {header.municipality||'—'}</td><td>Ward: {header.ward||'—'}</td></tr><tr><td>Report Month: {header.reportMonth}</td><td>Reference No.: {header.referenceNo}</td><td colSpan={2}>Subject: {header.subject}</td></tr></tbody></table>
 <Box className="hmis-grid" sx={{mt:1}}><Box><Typography fontWeight={700}>Age Group / Client Service</Typography><table><thead><tr><th rowSpan={2}>Age Group</th><th colSpan={2}>New Clients Served</th><th colSpan={2}>Total Clients Served</th><th colSpan={2}>Emergency Served</th></tr><tr>{CLIENT_METRICS.flatMap(m=>['Female','Male'].map(s=><th key={m+s}>{s}</th>))}</tr></thead><tbody>{AGE_GROUPS.map(a=><tr key={a}><td>{a}</td>{CLIENT_METRICS.flatMap(m=>['Female','Male'].map(s=>{const isAuto=m==='newClients';const val=isAuto?(auto.newClientsByAgeSex?.[a]?.[s]??0):manual.clients[a][m][s];return <td key={m+s}><CellInput label={`${a} ${m} ${s}`} disabled={isAuto||!editable} value={val} onChange={v=>update(['clients',a,m,s],v)}/></td>}))}</tr>)}</tbody></table><Source>New clients: Auto from LIS. Total Clients Served and emergency: Manual HMIS Entry.</Source>
 <Typography fontWeight={700} sx={{mt:1}}>Cases Diagnosed by Type</Typography><table><thead><tr><th>Condition</th><th>Female</th><th>Male</th></tr></thead><tbody>{CONDITIONS.map(x=><tr key={x}><td>{x}</td>{['Female','Male'].map(s=><td key={s}><CellInput label={`${x} ${s}`} disabled={!editable} value={manual.conditions[x][s]} onChange={v=>update(['conditions',x,s],v)}/></td>)}</tr>)}</tbody></table><Source>Manual Entry; never inferred from test names.</Source>
 <Typography fontWeight={700} sx={{mt:1}}>OPD Clinics / HCU</Typography><table><thead><tr><th>Activity</th><th>Planned / Total No.</th><th>Conducted / Report Received</th></tr></thead><tbody>{OPD_ROWS.map(x=><tr key={x}><td>{x}</td>{['planned','conducted'].map(s=><td key={s}><CellInput label={`${x} ${s}`} disabled={!editable} value={manual.opd[x][s]} onChange={v=>update(['opd',x,s],v)}/></td>)}</tr>)}</tbody></table>
 <Typography fontWeight={700} sx={{mt:1}}>Number of Service Sites / Referral Site</Typography><table><thead><tr><th>Site</th><th>Yes</th><th>No</th></tr></thead><tbody>{SERVICE_SITES.map(x=><tr key={x}><td>{x}</td><td>{config.serviceSites[x]?'✓':''}</td><td>{!config.serviceSites[x]?'✓':''}</td></tr>)}<tr><th colSpan={3}>Referral Site</th></tr>{REFERRAL_SITES.map(x=><tr key={x}><td>{x}</td><td>{config.referralSites[x]?'✓':''}</td><td>{!config.referralSites[x]?'✓':''}</td></tr>)}</tbody></table></Box>
 <Box><Typography fontWeight={700}>Diagnostic / Service Availability</Typography><table><thead><tr><th>Service</th><th>Status</th><th>Unit</th><th>Number</th></tr></thead><tbody>{SERVICES.map(x=><tr key={x}><td>{x}</td><td>{config.services[x]?.availability}</td><td>{config.services[x]?.unit}</td><td>{x==='Other Laboratory Services Provided'?(auto.totalInvestigations??0):config.services[x]?.availability==='Available'?'0':config.nonApplicableValue}</td></tr>)}</tbody></table><Source>Configured Facility Data; laboratory number is Auto from LIS.</Source>
 <Typography fontWeight={700} sx={{mt:1}}>Ownership / Capacity</Typography><p>Ownership Type: {config.ownershipType}</p><table><tbody>{CAPACITY_ROWS.map(x=><tr key={x}><td>{x}</td><td><CellInput label={x} disabled={!editable} value={manual.capacity[x]||config.nonApplicableValue} onChange={v=>update(['capacity',x],v)}/></td></tr>)}</tbody></table><Source>Manual Entry; defaults configured for non-applicable hospital fields.</Source>
 <Typography fontWeight={700} sx={{mt:1}}>Referrals</Typography><table><tbody>{Object.entries({Female:'Female',Male:'Male',referredIn:'Referred In',referredOut:'Referred Out',inPatient:'In-Patient',emergency:'Emergency'}).map(([k,l])=><tr key={k}><td>{l}</td><td><CellInput label={l} disabled={!editable} value={manual.referrals[k]} onChange={v=>update(['referrals',k],v)}/></td></tr>)}</tbody></table>
 <Typography fontWeight={700} sx={{mt:1}}>Minimum Service Standard (MSS)</Typography><p>Date: {manual.mss.date||'—'} · Implementation: {manual.mss.implementation} · Score (%): {manual.mss.score||'—'} <Source>Manual HMIS Entry</Source></p><Typography fontWeight={700}>Prepared By / Signature</Typography><p>Name: {prepared.name||'—'} · Designation: {prepared.designation||'—'} · Date: {manual.prepared.date?formatDualDate(manual.prepared.date):'—'} · Signature: {prepared.signatureUrl?'Selected personnel signature':'Not provided'}</p><p>Verified By: {identity(selected.verified)?.name||'—'} · Approved By: {identity(selected.approved)?.name||'—'}</p></Box></Box>
 <Typography sx={{mt:1,fontSize:10}}>LIS totals — registered patients: {auto.registeredPatients??0}; bills/visits: {auto.totalBillsVisits??0}; investigations: {auto.totalInvestigations??0}; completed tests: {auto.completedTests??0}; outsourced: {auto.outsourceCount??0}; reports: {auto.reportCount??0}; samples: {auto.sampleCount??0}. No patient identifiers included.</Typography><Typography sx={{fontSize:10}}>State: {report?.status??'Unsaved Draft'} · Version: {report?.current_version??0} · Generated by: {profile?.fullName??'Authenticated user'} · Period: {header.reportMonth}</Typography></CardContent></Card></div></>}
 {tab===1&&<Card sx={{mt:2}}><CardContent><Typography variant="h6">Immutable report history</Typography><table><thead><tr><th>Month</th><th>Fiscal Year</th><th>Status</th><th>Version</th><th>Finalized</th><th>Submitted</th></tr></thead><tbody>{history.map(r=><tr key={r.id}><td>{r.report_month}</td><td>{r.fiscal_year}</td><td>{r.status}</td><td>{r.current_version}</td><td>{r.finalized_at?formatDualDate(r.finalized_at):'—'}</td><td>{r.submitted_at?formatDualDate(r.submitted_at):'—'}</td></tr>)}</tbody></table></CardContent></Card>}
 {tab===2&&<Configuration config={config} setConfig={setConfig} save={saveConfig} editable={can(PERMISSION_KEYS.CAN_EDIT_HMIS_REPORTS)}/>}<Dialog open={submitOpen} onClose={()=>setSubmitOpen(false)}><DialogTitle>Record HMIS submission</DialogTitle><DialogContent><TextField fullWidth margin="dense" type="date" label="Submission Date" value={submission.date} onChange={e=>setSubmission({...submission,date:e.target.value})}/><TextField fullWidth margin="dense" label="Submitted To" value={submission.to} onChange={e=>setSubmission({...submission,to:e.target.value})}/><FormControl fullWidth margin="dense"><InputLabel>Method</InputLabel><Select label="Method" value={submission.method} onChange={e=>setSubmission({...submission,method:e.target.value})}>{['Physical','Email','Portal','Other'].map(x=><MenuItem key={x} value={x}>{x}</MenuItem>)}</Select></FormControl><TextField fullWidth margin="dense" label="Reference / Receipt No." value={submission.reference} onChange={e=>setSubmission({...submission,reference:e.target.value})}/><TextField fullWidth margin="dense" multiline label="Remarks" value={submission.remarks} onChange={e=>setSubmission({...submission,remarks:e.target.value})}/><Alert severity="info">Attachments remain optional and private; upload is not enabled in this release.</Alert></DialogContent><DialogActions><Button onClick={()=>setSubmitOpen(false)}>Cancel</Button><Button disabled={!submission.to||!submission.date} onClick={submit}>Record</Button></DialogActions></Dialog></Box>;
};

const Configuration=({config,setConfig,save,editable}:{config:HmisConfig;setConfig:(c:HmisConfig)=>void;save:()=>void;editable:boolean})=><Card sx={{mt:2}}><CardContent><Typography variant="h6">Configured Facility Data</Typography><Alert severity="warning" sx={{my:1}}>Nothing is marked available automatically. Confirm each facility/service setting explicitly.</Alert><Grid container spacing={1}>{(['facilityName','hfCode','province','district','municipality','ward','ownershipType','referencePrefix'] as const).map(k=><Grid item xs={12} sm={3} key={k}><TextField fullWidth size="small" label={k} disabled={!editable} value={config[k]} onChange={e=>setConfig({...config,[k]:e.target.value})}/></Grid>)}</Grid><Typography fontWeight={700} sx={{mt:2}}>Service availability</Typography>{SERVICES.map(x=><Box key={x} sx={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:1,my:.5}}><Typography>{x}</Typography><Select size="small" disabled={!editable} value={config.services[x]?.availability??'Not Applicable'} onChange={e=>setConfig({...config,services:{...config.services,[x]:{...config.services[x],availability:e.target.value as any}}})}>{['Available','Not Available','Not Applicable'].map(v=><MenuItem key={v} value={v}>{v}</MenuItem>)}</Select><TextField size="small" label="Unit" disabled={!editable} value={config.services[x]?.unit??''} onChange={e=>setConfig({...config,services:{...config.services,[x]:{...config.services[x],unit:e.target.value}}})}/></Box>)}<Typography fontWeight={700}>Sites</Typography><Box sx={{display:'flex',flexWrap:'wrap',gap:1}}>{[...SERVICE_SITES,...REFERRAL_SITES].map(x=>{const referral=(REFERRAL_SITES as readonly string[]).includes(x);const values=referral?config.referralSites:config.serviceSites;return <Chip key={x} clickable disabled={!editable} color={values[x]?'success':'default'} label={`${x}: ${values[x]?'Yes':'No'}`} onClick={()=>setConfig({...config,[referral?'referralSites':'serviceSites']:{...values,[x]:!values[x]}})}/>})}</Box><Button sx={{mt:2}} variant="contained" disabled={!editable} onClick={save}>Save Configuration</Button></CardContent></Card>;
