import 'regenerator-runtime/runtime.js';
import fontkit from '@pdf-lib/fontkit';
import { PDFDocument, PDFFont, PDFImage, PDFPage, rgb } from 'pdf-lib';
import QRCode from 'qrcode';

const encoder=new TextEncoder(),A4:[number,number]=[595.28,841.89];
const BRAND=rgb(11/255,107/255,58/255),BRAND_DARK=rgb(7/255,78/255,42/255),MINT=rgb(237/255,247/255,241/255),INK=rgb(15/255,23/255,42/255),MUTED=rgb(71/255,85/255,105/255),BORDER=rgb(199/255,216/255,207/255),DANGER=rgb(185/255,28/255,28/255);
export interface SignatureAsset{bytes:Uint8Array;mimeType:'image/png'|'image/jpeg'}
export interface PdfAssets{latinFont:Uint8Array;devanagariFont:Uint8Array;logoPng?:Uint8Array;publicUrl:string;reportNumber:string;performedSignature?:SignatureAsset;authorizedSignature?:SignatureAsset}
type Fonts={latin:PDFFont;deva:PDFFont};type Row={kind:'section'|'result'|'note';section?:string;test?:string;method?:string;name?:string;value?:string;unit?:string;range?:string;flag?:string;note?:string};

export function canonicalJson(value:unknown):string{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonicalJson).join(',')}]`;return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${canonicalJson(v)}`).join(',')}}`}
export async function sha256Hex(value:Uint8Array|string){const bytes=typeof value==='string'?encoder.encode(value):value,input=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;return [...new Uint8Array(await crypto.subtle.digest('SHA-256',input))].map(x=>x.toString(16).padStart(2,'0')).join('')}
const string=(v:unknown,fallback='—')=>typeof v==='string'&&v.trim()?v.trim():fallback;
const isDeva=(c:string)=>{const n=c.codePointAt(0)??0;return n>=0x0900&&n<=0x097f};
const charSetCache=new WeakMap<PDFFont,Set<number>>();
const supported=(f:PDFFont,c:string)=>{let set=charSetCache.get(f);if(!set){set=new Set(f.getCharacterSet());charSetCache.set(f,set)}return set.has(c.codePointAt(0)??-1)};
function clean(value:unknown,fonts:Fonts){return String(value??'—').replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/./gu,c=>supported(isDeva(c)?fonts.deva:fonts.latin,c)||supported(fonts.deva,c)||supported(fonts.latin,c)?c:'?')}
function runs(text:string,fonts:Fonts){const out:{text:string;font:PDFFont}[]=[];for(const c of text){const preferred=isDeva(c)?fonts.deva:fonts.latin,font=supported(preferred,c)?preferred:supported(fonts.deva,c)?fonts.deva:fonts.latin,last=out.at(-1);if(last?.font===font)last.text+=c;else out.push({text:c,font})}return out}
function width(text:string,size:number,fonts:Fonts){return runs(clean(text,fonts),fonts).reduce((n,r)=>n+r.font.widthOfTextAtSize(r.text,size),0)}
function drawText(page:PDFPage,text:string,x:number,y:number,size:number,fonts:Fonts,color=INK,maxWidth?:number){let cursor=x;for(const r of runs(clean(text,fonts),fonts)){if(maxWidth&&cursor-x+r.font.widthOfTextAtSize(r.text,size)>maxWidth)break;page.drawText(r.text,{x:cursor,y,size,font:r.font,color});cursor+=r.font.widthOfTextAtSize(r.text,size)}return cursor}
function wrap(text:string,max:number,size:number,fonts:Fonts){const words=clean(text,fonts).split(/\s+/u),lines:string[]=[];let line='';for(const word of words){const candidate=line?`${line} ${word}`:word;if(width(candidate,size,fonts)<=max){line=candidate;continue}if(line)lines.push(line);if(width(word,size,fonts)<=max){line=word;continue}let chunk='';for(const c of word){if(chunk&&width(chunk+c,size,fonts)>max){lines.push(chunk);chunk=c}else chunk+=c}line=chunk}if(line)lines.push(line);return lines.length?lines:['—']}
function fit(text:string,max:number,size:number,fonts:Fonts){const t=clean(text,fonts);if(width(t,size,fonts)<=max)return t;let out='';for(const c of t){if(width(`${out}${c}…`,size,fonts)>max)break;out+=c}return `${out}…`}
function field(page:PDFPage,label:string,value:unknown,x:number,y:number,w:number,fonts:Fonts){drawText(page,label.toUpperCase(),x,y+10,6.2,fonts,MUTED,w);drawText(page,fit(String(value??'—'),w,8.2,fonts),x,y,8.2,fonts,INK,w)}
function flag(v:unknown){switch(String(v)){case'CriticalLow':return'LL';case'CriticalHigh':return'HH';case'Low':return'L';case'High':return'H';case'Abnormal':return'A';default:return''}}
function sectionName(v:unknown){const d=String(v??'').toLowerCase();if(d==='hematology')return'HEMATOLOGY';if(d==='biochemistry')return'CLINICAL BIOCHEMISTRY';if(d==='serology'||d==='immunology')return'SEROLOGY & IMMUNOLOGY';return string(v,'CLINICAL PATHOLOGY').toUpperCase()}
function rows(snapshot:any):Row[]{const out:Row[]=[];for(const inv of Array.isArray(snapshot?.investigations)?snapshot.investigations:[]){out.push({kind:'section',section:sectionName(inv.department),test:string(inv.test_name),method:inv.method?`Method: ${inv.method}`:''});for(const r of Array.isArray(inv.results)?inv.results:[])out.push({kind:'result',name:string(r.name),value:string(r.display_value),unit:string(r.unit,'-'),range:string(r.reference_range??(r.normal_min!=null&&r.normal_max!=null?`${r.normal_min} - ${r.normal_max}`:'Standard')),flag:flag(r.flag)});if(inv.interpretation_template)out.push({kind:'note',note:string(inv.interpretation_template)})}return out}
function rowHeight(r:Row,f:Fonts){if(r.kind==='section')return 29;if(r.kind==='note')return 20+wrap(r.note??'',500,7.2,f).length*9;return Math.max(18,wrap(r.name??'',205,7.4,f).length*9,wrap(r.value??'',88,7.4,f).length*9)}
function paginate(all:Row[],fonts:Fonts){const pages:Row[][]=[];let current:Row[]=[],used=0,lastSection:Row|undefined;for(const row of all){const h=rowHeight(row,fonts);if(row.kind==='section')lastSection=row;if(current.length&&used+h>405){pages.push(current);current=[];used=0;if(row.kind==='result'&&lastSection){current.push({...lastSection,test:`${lastSection.test} — continued`});used=29}}current.push(row);used+=h}if(current.length||!pages.length)pages.push(current);return pages}
function decodeDataImage(value:unknown){if(typeof value!=='string')return null;const m=value.match(/^data:image\/(png|jpeg);base64,([A-Za-z0-9+/=]+)$/);if(!m)return null;const raw=atob(m[2]);if(raw.length>512_000)return null;const bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return{kind:m[1],bytes}}
async function embedSignature(pdf:PDFDocument,value:unknown){const p=decodeDataImage(value);if(!p)return null;try{return p.kind==='png'?await pdf.embedPng(p.bytes):await pdf.embedJpg(p.bytes)}catch{return null}}
async function embedSignatureAsset(pdf:PDFDocument,asset:SignatureAsset|undefined,value:unknown){if(asset){if(asset.bytes.byteLength>512_000)return null;try{return asset.mimeType==='image/png'?await pdf.embedPng(asset.bytes):await pdf.embedJpg(asset.bytes)}catch{return null}}return embedSignature(pdf,value)}
function drawImageContained(page:PDFPage,image:PDFImage,x:number,y:number,w:number,h:number){const scale=Math.min(w/image.width,h/image.height),iw=image.width*scale,ih=image.height*scale;page.drawImage(image,{x:x+(w-iw)/2,y:y+(h-ih)/2,width:iw,height:ih})}
function drawQr(page:PDFPage,url:string,x:number,y:number,size:number){const qr=QRCode.create(url,{errorCorrectionLevel:'M'}),n=qr.modules.size,data=qr.modules.data as Uint8Array,quiet=4,module=size/(n+quiet*2);page.drawRectangle({x,y,width:size,height:size,color:rgb(1,1,1)});for(let r=0;r<n;r++)for(let c=0;c<n;c++)if(data[r*n+c])page.drawRectangle({x:x+(c+quiet)*module,y:y+size-(r+quiet+1)*module,width:module+.05,height:module+.05,color:INK})}

function drawIdentityMark(page:PDFPage,f:Fonts){page.drawCircle({x:63.5,y:777.5,size:25,borderColor:BRAND_DARK,borderWidth:2});page.drawCircle({x:63.5,y:777.5,size:20,borderColor:BRAND,borderWidth:.8});drawText(page,'BP',48,771,14,f,BRAND_DARK,31);drawText(page,'LAB',53,760,5.5,f,BRAND,22)}
function drawHeader(page:PDFPage,s:any,reportNo:string,version:number,amended:boolean,url:string,f:Fonts,logo?:PDFImage):void;
function drawHeader(page:PDFPage,s:any,reportNo:string,version:number,amended:boolean,url:string,f:Fonts){const org=s?.organization??{},p=s?.patient??{},o=s?.order??{};page.drawRectangle({x:28,y:662,width:539,height:150,borderColor:BRAND,borderWidth:1});drawIdentityMark(page,f);drawText(page,string(org.name_en,'BIMAL PATHOLOGY & DIAGNOSTIC CENTER'),100,789,13,f,BRAND_DARK,350);drawText(page,string(org.name_ne,'बिमल प्याथोलोजी एण्ड डायग्नोस्टिक सेन्टर'),100,770,10.5,f,BRAND,350);drawText(page,`${string(org.address_en,'Bharatpur-7, Chitwan, Nepal')}  |  ${string(org.phone,'056-593288')}`,100,754,7.2,f,MUTED,350);drawText(page,`Reg: ${string(org.reg_no,'7-1496')}  |  PAN: ${string(org.pan_no,'302481477')}`,100,741,7.2,f,MUTED,350);drawQr(page,url,493,750,60);drawText(page,'SCAN TO VERIFY',493,740,5.5,f,MUTED,60);page.drawRectangle({x:36,y:706,width:517,height:27,color:amended?rgb(1,.95,.89):MINT});drawText(page,amended?'AMENDED DIAGNOSTIC REPORT':'DIAGNOSTIC PATHOLOGY REPORT',45,716,10,f,amended?DANGER:BRAND_DARK,300);drawText(page,`${reportNo}  •  Version ${version}`,365,716,8.5,f,INK,180);const age=p.age_years?`${p.age_years} Y`:p.age_months?`${p.age_months} M`:p.age_days?`${p.age_days} D`:'—';field(page,'Patient',`${p.title??''} ${string(p.full_name)}`.trim(),39,684,170,f);field(page,'UHID',p.uhid,218,684,100,f);field(page,'Age / Sex',`${age} / ${string(p.gender)}`,327,684,100,f);field(page,'BPDC Lab No.',o.order_number,436,684,113,f);field(page,'Referrer',o.referring_doctor_name,39,666,170,f);field(page,'Registered',o.registered_date_ad??o.registered_date_bs,218,666,100,f);field(page,'Collected',o.collected_at,327,666,100,f);field(page,'Reported',o.reported_at,436,666,113,f)}
function drawTable(page:PDFPage,rs:Row[],f:Fonts){let y=650;const x=36,w=517;page.drawRectangle({x,y:y-18,width:w,height:18,color:MINT,borderColor:BORDER,borderWidth:.5});[['TEST / PARAMETER',0],['FLAG',213],['VALUE',255],['UNIT',350],['REFERENCE RANGE',415]].forEach(([t,o])=>drawText(page,String(t),x+5+Number(o),y-12,6.5,f,BRAND_DARK));y-=18;for(const r of rs){const h=rowHeight(r,f);if(r.kind==='section'){page.drawRectangle({x,y:y-h,width:w,height:h,color:BRAND});drawText(page,r.section??'',x+7,y-11,6.5,f,rgb(1,1,1),175);drawText(page,r.test??'',x+184,y-11,8.5,f,rgb(1,1,1),260);if(r.method)drawText(page,r.method,x+184,y-22,6.2,f,rgb(.9,.97,.93),260)}else if(r.kind==='note'){page.drawRectangle({x,y:y-h,width:w,height:h,color:rgb(.97,.985,.975),borderColor:BORDER,borderWidth:.5});drawText(page,'CLINICAL NOTE / REMARKS',x+6,y-11,6.3,f,BRAND_DARK);wrap(r.note??'',w-12,7.2,f).forEach((line,i)=>drawText(page,line,x+6,y-22-i*9,7.2,f,INK,w-12))}else{page.drawRectangle({x,y:y-h,width:w,height:h,borderColor:rgb(.91,.94,.92),borderWidth:.35});const abnormal=Boolean(r.flag);wrap(r.name??'',205,7.4,f).forEach((line,i)=>drawText(page,line,x+5,y-12-i*9,7.4,f,INK,205));drawText(page,r.flag??'',x+224,y-12,7.5,f,abnormal?DANGER:INK,32);wrap(r.value??'',88,7.4,f).forEach((line,i)=>drawText(page,line,x+260,y-12-i*9,7.4,f,abnormal?DANGER:INK,88));drawText(page,fit(r.unit??'',60,7,f),x+355,y-12,7,f,MUTED,60);drawText(page,fit(r.range??'',96,7,f),x+420,y-12,7,f,INK,92)}y-=h}}
function drawSignature(page:PDFPage,title:string,p:any,image:PDFImage|null,x:number,y:number,w:number,f:Fonts){drawText(page,title,x,y+52,6.5,f,BRAND_DARK,w);page.drawLine({start:{x,y:y+48},end:{x:x+w,y:y+48},thickness:.5,color:BORDER});if(image)drawImageContained(page,image,x,y+20,100,26);else drawText(page,'Signature evidence not recorded',x,y+31,6,f,MUTED,w);drawText(page,string(p?.full_name,'Not recorded'),x,y+10,7.5,f,INK,w);drawText(page,fit(`${string(p?.qualification,'—')} | ${string(p?.registration_council,'Registration')}: ${string(p?.registration_number,'—')}`,w,6.2,f),x,y,6.2,f,MUTED,w)}
function drawFooter(page:PDFPage,s:any,no:number,total:number,hash:string,f:Fonts,performed:PDFImage|null,authorized:PDFImage|null){const sig=s?.signatories??{};page.drawRectangle({x:28,y:52,width:539,height:70,borderColor:BRAND,borderWidth:1});drawSignature(page,'REPORTED / PERFORMED BY',sig.performed_by,performed,38,61,sig.authorized_by?240:500,f);if(sig.authorized_by)drawSignature(page,'VERIFIED / AUTHORIZED BY',sig.authorized_by,authorized,310,61,240,f);page.drawRectangle({x:28,y:25,width:539,height:21,color:BRAND});drawText(page,'Results relate only to the specimen tested and require clinical correlation.',36,33,6.2,f,rgb(1,1,1),315);drawText(page,`Integrity: ${hash.slice(0,16)}…`,355,33,6.1,f,rgb(1,1,1),145);drawText(page,`Page ${no} of ${total}`,505,33,6.5,f,rgb(1,1,1),55)}

export async function renderFrozenSnapshotPdf(snapshot:unknown,reportIntegrityHash:string,assets?:PdfAssets):Promise<Uint8Array>{
  if(!assets)throw new Error('PDF_ASSETS_REQUIRED');
  if(!/^https:\/\/(?:lis[.]bimalpathology[.]com[.]np\/r|dashboard[.]bimalpathology[.]com[.]np\/[ro])\/[A-Za-z0-9_-]{32,256}$/.test(assets.publicUrl))throw new Error('QR_PUBLIC_URL_UNAVAILABLE');
  if(!/^[0-9a-f]{64}$/.test(reportIntegrityHash))throw new Error('INVALID_REPORT_INTEGRITY_HASH');
  if(!assets.reportNumber.trim())throw new Error('REPORT_NUMBER_REQUIRED');
  const pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);
  pdf.setTitle('Bimal Pathology Authoritative Diagnostic Report');pdf.setAuthor('Bimal Pathology & Diagnostic Center');
  pdf.setProducer('bimal-pathology-frozen-snapshot-pdf/2.1.0');pdf.setCreator('bimal-pathology-report-artifacts');
  const epoch=new Date('2000-01-01T00:00:00.000Z');pdf.setCreationDate(epoch);pdf.setModificationDate(epoch);
  const latin=await pdf.embedFont(assets.latinFont,{subset:false}),deva=await pdf.embedFont(assets.devanagariFont,{subset:false}),f:Fonts={latin,deva};
  const logo=assets.logoPng?await pdf.embedPng(assets.logoPng):undefined,s=snapshot as any;
  const performed=await embedSignatureAsset(pdf,assets.performedSignature,s?.signatories?.performed_by?.signature_data_url);
  const authorized=await embedSignatureAsset(pdf,assets.authorizedSignature,s?.signatories?.authorized_by?.signature_data_url);
  const all=rows(s),pages=paginate(all,f),reportNo=assets.reportNumber,version=Number(s?.meta?.version??1),amended=Boolean(s?.meta?.is_amendment),snapshotHash=await sha256Hex(canonicalJson(snapshot));
  for(let i=0;i<pages.length;i++){const page=pdf.addPage(A4);drawHeader(page,s,reportNo,version,amended,assets.publicUrl,f,logo);drawTable(page,pages[i],f);if(i===pages.length-1){drawText(page,'* END OF REPORT *',235,137,7,f,BRAND_DARK,130);if(amended)drawText(page,fit(`Amendment reason: ${string(s?.meta?.amendment_reason)}`,500,6.5,f),38,128,6.5,f,DANGER,500)}drawFooter(page,s,i+1,pages.length,reportIntegrityHash,f,performed,authorized);drawText(page,`Frozen-Snapshot-SHA256: ${snapshotHash}`,36,16,5,f,MUTED,300)}
  return pdf.save({useObjectStreams:false,addDefaultPage:false,objectsPerTick:Infinity,updateFieldAppearances:false});
}
export function artifactKey(createdAt:string,reportId:string,version:number,hash:string){const year=new Date(createdAt).getUTCFullYear();if(!/^[0-9a-f-]{36}$/.test(reportId)||!Number.isInteger(version)||version<1||!/^[0-9a-f]{64}$/.test(hash))throw new Error('Invalid artifact identity');return `reports/${year}/${reportId}/v${version}/${hash}.pdf`}
