import test from 'node:test';import assert from 'node:assert/strict';import {SparrowProvider} from '../src/providers/sparrow/SparrowProvider.js';
const message={queueId:'q',recipient:'9800000000',body:'hello'};
test('accepted Sparrow response requires code and message ID',async()=>{const p=new SparrowProvider('t','s',(async()=>new Response(JSON.stringify({response_code:200,message_id:'id',count:1}),{status:200,headers:{'content-type':'application/json'}})) as typeof fetch);assert.equal((await p.send(message,AbortSignal.timeout(1000))).outcome,'accepted');});
test('Sparrow form fields are exact and ordered',async()=>{let body='';const p=new SparrowProvider('t','s',(async(_u:unknown,i?:RequestInit)=>{body=String(i?.body);return new Response(JSON.stringify({response_code:200,message_id:'id'}),{status:200,headers:{'content-type':'application/json'}});}) as typeof fetch);await p.send(message,AbortSignal.timeout(1000));assert.equal(body,'token=t&from=s&to=9800000000&text=hello');});
test('HTTP 429 is retryable',async()=>{const p=new SparrowProvider('t','s',(async()=>new Response(JSON.stringify({response_code:429}),{status:429,headers:{'content-type':'application/json'}})) as typeof fetch);assert.equal((await p.send(message,AbortSignal.timeout(1000))).outcome,'retryable_failure');});
test('HTTP 403 is provider unavailable',async()=>{const p=new SparrowProvider('t','s',(async()=>new Response('{}',{status:403,headers:{'content-type':'application/json'}})) as typeof fetch);assert.equal((await p.send(message,AbortSignal.timeout(1000))).outcome,'provider_unavailable');});
test('permanent Sparrow code is not retried',async()=>{const p=new SparrowProvider('t','s',(async()=>new Response(JSON.stringify({response_code:1002}),{status:400,headers:{'content-type':'application/json'}})) as typeof fetch);assert.equal((await p.send(message,AbortSignal.timeout(1000))).outcome,'permanent_failure');});
test('malformed response is unknown outcome',async()=>{const p=new SparrowProvider('t','s',(async()=>new Response('bad',{status:200})) as typeof fetch);assert.equal((await p.send(message,AbortSignal.timeout(1000))).outcome,'unknown_outcome');});
test('missing provider configuration fails without transport',()=>assert.throws(()=>new SparrowProvider('','s').validateConfiguration(),/CONFIGURATION/));
