import test from 'node:test';import assert from 'node:assert/strict';import type {GatewaySecrets} from '../src/config/GatewayConfig.js';import {GatewayAuth} from '../src/supabase/GatewayAuth.js';import {GatewayRpcClient} from '../src/supabase/GatewayRpcClient.js';
const secrets:GatewaySecrets={supabaseUrl:'https://isolated.invalid.supabase.co',supabasePublishableKey:'publishable-test',gatewayEmail:'gateway@test.invalid',gatewayPassword:'password-test',sparrowToken:'provider-test',sparrowSender:'sender'};
function authFetch():typeof fetch{return (async()=>new Response(JSON.stringify({access_token:'mock-access',expires_in:3600}),{status:200,headers:{'content-type':'application/json'}})) as typeof fetch;}
test('Gateway Auth uses publishable key and password grant',async()=>{let request:RequestInit|undefined;const f=(async(_u:unknown,i?:RequestInit)=>{request=i;return new Response(JSON.stringify({access_token:'mock-access',expires_in:3600}),{status:200,headers:{'content-type':'application/json'}});}) as typeof fetch;await new GatewayAuth(secrets,f).getAccessToken();assert.equal((request?.headers as Record<string,string>).apikey,'publishable-test');assert.match(String(request?.body),/gateway@test\.invalid/);});
test('Gateway Auth caches unexpired access token',async()=>{let calls=0;const f=(async()=>{calls++;return new Response(JSON.stringify({access_token:'mock-access',expires_in:3600}),{status:200,headers:{'content-type':'application/json'}});}) as typeof fetch;const auth=new GatewayAuth(secrets,f);await auth.getAccessToken();await auth.getAccessToken();assert.equal(calls,1);});
test('RPC client calls only named Gateway preflight',async()=>{let url='';let body='';const f=(async(u:unknown,i?:RequestInit)=>{url=String(u);body=String(i?.body);return new Response('{}',{status:200,headers:{'content-type':'application/json'}});}) as typeof fetch;const c=new GatewayRpcClient(secrets,new GatewayAuth(secrets,authFetch()),5000,f);await c.preflight('instance');assert.match(url,/rpc\/sms_gateway_v2_preflight$/);assert.match(body,/p_instance_id/);});
test('claim contract sends stable instance and worker identity',async()=>{let body='';const f=(async(_u:unknown,i?:RequestInit)=>{body=String(i?.body);return new Response('[]',{status:200,headers:{'content-type':'application/json'}});}) as typeof fetch;const c=new GatewayRpcClient(secrets,new GatewayAuth(secrets,authFetch()),5000,f);await c.claim('instance','worker',1,300);assert.deepEqual(JSON.parse(body),{p_instance_id:'instance',p_worker_id:'worker',p_batch_size:1,p_lease_seconds:300});});
test('unknown provider result maps to quarantine classification',async()=>{let body='';const f=(async(_u:unknown,i?:RequestInit)=>{body=String(i?.body);return new Response('{}',{status:200,headers:{'content-type':'application/json'}});}) as typeof fetch;const c=new GatewayRpcClient(secrets,new GatewayAuth(secrets,authFetch()),5000,f);await c.complete('instance','item','worker',{accepted:false,outcome:'unknown_outcome'});assert.equal(JSON.parse(body).p_error_classification,'ProviderOutcomeUnknown');assert.equal(JSON.parse(body).p_retryable,false);});
test('HTTP 401 invalidates the Gateway session',async()=>{let calls=0;const auth=new GatewayAuth(secrets,authFetch());const f=(async()=>{calls++;return new Response('',{status:401});}) as typeof fetch;const c=new GatewayRpcClient(secrets,auth,5000,f);await assert.rejects(c.preflight('instance'),/authentication rejected/);assert.equal(calls,1);});
