import test from 'node:test';import assert from 'node:assert/strict';import type {GatewayConfig} from '../src/config/GatewayConfig.js';import {GatewayWorker} from '../src/app/GatewayWorker.js';import {HealthState} from '../src/observability/HealthState.js';
const base:GatewayConfig={instanceId:'11111111-1111-4111-8111-111111111111',version:'2.0.0-clean.1',mode:'active',pollMs:1000,heartbeatMs:30000,rpcTimeoutMs:5000,providerTimeoutMs:5000,leaseSeconds:300,claimBatchSize:1,maxConcurrency:1,maxSegments:3,shutdownMs:1000,dataDirectory:'test'};
const logger={info:async()=>{},warn:async()=>{},error:async()=>{}};
function row(){return{id:'q',sms_type:'BillRegistration',recipient_phone:'9800000000',message_body:'hello',retry_count:0,max_attempts:5,idempotency_key:'k',lease_owner:'w'};}
test('shadow run executes preflight only',async()=>{const calls:string[]=[];const queue={preflight:async()=>{calls.push('preflight')},recover:async()=>calls.push('recover'),claim:async()=>{calls.push('claim');return[]}};const provider={name:'mock',validateConfiguration(){},async send(){calls.push('send');return{outcome:'accepted' as const}}};const h=new HealthState(base.instanceId,'w',base.version,'shadow');await new GatewayWorker({...base,mode:'shadow'},queue as never,provider, h,logger as never).run(new AbortController().signal);assert.deepEqual(calls,['preflight']);});
test('direct poll is hard-blocked in shadow mode',async()=>{const worker=new GatewayWorker({...base,mode:'shadow'},{} as never,{} as never,new HealthState(base.instanceId,'w',base.version,'shadow'),logger as never);await assert.rejects(worker.poll(),/SHADOW_MODE_QUEUE_ACCESS_BLOCKED/);});
test('active delivery fences before provider and completes after',async()=>{const calls:string[]=[];const queue={recover:async()=>calls.push('recover'),claim:async()=>{calls.push('claim');return[row()]},markStarted:async()=>{calls.push('fence');return true},complete:async()=>calls.push('complete'),rejectLocal:async()=>calls.push('reject')};const provider={name:'mock',validateConfiguration(){},async send(){calls.push('send');return{outcome:'accepted' as const,providerMessageId:'id'}}};const h=new HealthState(base.instanceId,'w',base.version,'active');await new GatewayWorker(base,queue as never,provider,h,logger as never).poll();await new Promise(r=>setTimeout(r,10));assert.deepEqual(calls,['recover','claim','fence','send','complete']);});
test('invalid Nepal mobile rejects before provider fence',async()=>{const calls:string[]=[];const queue={recover:async()=>{},claim:async()=>[{...row(),recipient_phone:'123'}],markStarted:async()=>{calls.push('fence');return true},complete:async()=>calls.push('complete'),rejectLocal:async()=>calls.push('reject')};const provider={name:'mock',validateConfiguration(){},async send(){calls.push('send');return{outcome:'accepted' as const}}};await new GatewayWorker(base,queue as never,provider,new HealthState(base.instanceId,'w',base.version,'active'),logger as never).poll();await new Promise(r=>setTimeout(r,10));assert.deepEqual(calls,['reject']);});
test('provider throw after fence becomes unknown outcome completion',async()=>{let completion:unknown;const queue={recover:async()=>{},claim:async()=>[row()],markStarted:async()=>true,complete:async(...args:unknown[])=>{completion=args[3]},rejectLocal:async()=>{}};const provider={name:'mock',validateConfiguration(){},async send(){throw new Error('ambiguous')}};await new GatewayWorker(base,queue as never,provider,new HealthState(base.instanceId,'w',base.version,'active'),logger as never).poll();await new Promise(r=>setTimeout(r,10));assert.equal((completion as {outcome:string}).outcome,'unknown_outcome');});
test('lease loss prevents provider invocation',async()=>{let sends=0;const queue={recover:async()=>{},claim:async()=>[row()],markStarted:async()=>false,complete:async()=>{},rejectLocal:async()=>{}};const provider={name:'mock',validateConfiguration(){},async send(){sends++;return{outcome:'accepted' as const}}};await new GatewayWorker(base,queue as never,provider,new HealthState(base.instanceId,'w',base.version,'active'),logger as never).poll();await new Promise(r=>setTimeout(r,10));assert.equal(sends,0);});
test('explicit process worker identity is used for claims and health correlation',()=>{const worker=new GatewayWorker(base,{} as never,{} as never,new HealthState(base.instanceId,'process-worker',base.version,'active'),logger as never,'process-worker');assert.equal(worker.workerId,'process-worker');});
test('idle shutdown cancels the losing drain timer',async()=>{const controller=new AbortController();controller.abort();const worker=new GatewayWorker(base,{} as never,{} as never,new HealthState(base.instanceId,'worker',base.version,'active'),logger as never);const started=performance.now();await worker.run(controller.signal);assert.ok(performance.now()-started<200);});
test('shutdown stops new claims and drains an already fenced delivery',async()=>{const calls:string[]=[];let release!:()=>void;const providerWait=new Promise<void>(resolve=>release=resolve);const queue={recover:async()=>calls.push('recover'),claim:async()=>{calls.push('claim');return[row()]},markStarted:async()=>{calls.push('fence');return true},complete:async()=>calls.push('complete'),rejectLocal:async()=>{}};const provider={name:'mock',validateConfiguration(){},async send(){calls.push('send');await providerWait;return{outcome:'accepted' as const,providerMessageId:'id'}}};const controller=new AbortController();const worker=new GatewayWorker({...base,pollMs:10},queue as never,provider,new HealthState(base.instanceId,'worker',base.version,'active'),logger as never);const running=worker.run(controller.signal);while(!calls.includes('send'))await new Promise(resolve=>setTimeout(resolve,1));controller.abort();release();await running;assert.deepEqual(calls,['recover','claim','fence','send','complete']);});

test('URL queue rows including resends are rejected and audited before fence', async () => {
 const calls: string[]=[];
 const queue={recover:async()=>{},claim:async()=>[{...row(),message_body:'Report: https://lis.bimalpathology.com.np/r/secret'}],rejectLocal:async(_i:unknown,_q:unknown,_w:unknown,code:string)=>{calls.push(code)},markStarted:async()=>{throw new Error('must not fence')}};
 const provider={name:'mock',validateConfiguration(){},async send(){throw new Error('must not send')}};
 const audit={...logger,warn:async(event:string,data:unknown)=>{calls.push(event);assert.equal(JSON.stringify(data).includes('secret'),false)}};
 await new GatewayWorker(base,queue as never,provider as never,new HealthState(base.instanceId,'w',base.version,'active'),audit as never).poll();
 await new Promise(resolve=>setTimeout(resolve,10));
 assert.deepEqual(calls,['SMS_URL_BLOCKED','sms.content_rejected']);
});
