import fs from'node:fs';import path from'node:path';import{createCanvas}from'@napi-rs/canvas';
const root=path.resolve(import.meta.dirname,'..');
const signature=()=>{const c=createCanvas(320,90),x=c.getContext('2d');x.clearRect(0,0,320,90);x.strokeStyle='#143f2b';x.lineWidth=5;x.lineCap='round';x.beginPath();x.moveTo(12,65);x.bezierCurveTo(55,5,72,82,112,32);x.bezierCurveTo(145,2,154,78,205,35);x.bezierCurveTo(238,15,260,62,305,20);x.stroke();return c.toDataURL('image/png')};
export const TOKEN='T'.repeat(48),PUBLIC_URL=`https://lis.bimalpathology.com.np/r/${TOKEN}`;
export const assets={latinFont:fs.readFileSync(path.join(root,'src/assets/noto-sans-latin.ttf')),devanagariFont:fs.readFileSync(path.join(root,'src/assets/noto-sans-devanagari.ttf')),logoPng:fs.readFileSync(path.join(root,'src/assets/pathology-logo.png')),publicUrl:PUBLIC_URL,reportNumber:'REP-2026-00001'};
const result=(i,over={})=>({parameter_id:`p-${i}`,code:`P${i}`,name:`Clinical Parameter ${i}`,value_type:'Numeric',display_value:String((i+1)*1.25),numeric_value:(i+1)*1.25,unit:i%3===0?'µmol/L':'g/dL',flag:'Normal',is_critical:false,reference_range:'1.0 - 9.5',...over});
export const baseSnapshot={organization:{name_en:'BIMAL PATHOLOGY & DIAGNOSTIC CENTER',name_ne:'बिमल प्याथोलोजी एण्ड डायग्नोस्टिक सेन्टर',address_en:'Bharatpur-7, Chitwan, Nepal',address_ne:'भरतपुर-७, चितवन, नेपाल',reg_no:'7-1496',pan_no:'302481477',phone:'056-593288'},patient:{uhid:'2608290001',full_name:'Synthetic Patient',title:'Mr.',mobile:'9800000000',gender:'Male',age_years:34,address:'Synthetic Address'},order:{order_number:'BPDC-260829-001',bill_number:'INV-0001',registered_date_ad:'2026-08-29',registered_date_bs:'2083-05-13',collected_at:'2026-08-29 09:00',received_at:'2026-08-29 09:15',reported_at:'2026-08-29 10:00',referring_doctor_name:'Dr. Synthetic Referrer'},signatories:{performed_by:{id:'person-1',full_name:'Synthetic Technologist',qualification:'BMLT',professional_type:'Lab Technologist',registration_council:'NHPC',registration_number:'SYN-001',signature_data_url:signature()},authorized_by:{id:'person-2',full_name:'Synthetic Pathologist',qualification:'MD Pathology',professional_type:'Pathologist',registration_council:'NMC',registration_number:'SYN-002',signature_data_url:signature()}},investigations:[{order_item_id:'item-1',test_id:'test-cbc',test_name:'Complete Blood Count',department:'Hematology',reporting_type:'InHouse',method:'Automated impedance',specimen_type:'Whole Blood',container_type:'EDTA',results:[result(0,{name:'Hemoglobin',display_value:'12.5'}),result(1,{name:'Total Leukocyte Count',display_value:'6500',unit:'/µL'})]}],meta:{report_number:'REP-2026-00001',version:1,is_amendment:false,amendment_reason:null,signed_at:'2026-08-29T04:15:00Z'}};
const clone=x=>structuredClone(x);
export function fixtures(){const simple=clone(baseSnapshot),multi=clone(baseSnapshot);multi.investigations=[{...multi.investigations[0],test_name:'Whole Body Extended Profile',results:Array.from({length:62},(_,i)=>result(i))}];const abnormal=clone(baseSnapshot);abnormal.investigations[0].results.push(result(3,{name:'Critical Potassium',display_value:'2.1',unit:'mmol/L',flag:'CriticalLow',is_critical:true}));const calculated=clone(baseSnapshot);calculated.investigations[0].results.push(result(4,{name:'Calculated LDL',value_type:'Calculated',display_value:'102.4',formula:'TC-HDL-TG/5'}));const amended=clone(baseSnapshot);amended.meta={...amended.meta,version:2,is_amendment:true,amendment_reason:'Corrected verified platelet count',report_number:'REP-2026-00001-A2'};const nepali=clone(baseSnapshot);nepali.patient.full_name='सीता श्रेष्ठ';nepali.patient.address='भरतपुर-७, चितवन';nepali.investigations[0].results[0].name='हेमोग्लोबिन परीक्षण';const mixed=clone(baseSnapshot);mixed.investigations[0].results.push(result(5,{name:'Mixed नेपाली Glucose Δ',display_value:'५.६ mmol/L'}));const profile=clone(baseSnapshot);profile.investigations.push({...profile.investigations[0],order_item_id:'item-2',test_id:'test-lft',test_name:'Liver Function Profile',department:'Biochemistry',results:Array.from({length:8},(_,i)=>result(i+10))});const long=clone(baseSnapshot);long.patient.full_name='Synthetic Patient With An Intentionally Very Long Frozen Historical Name That Must Not Overflow';long.order.referring_doctor_name='Dr. Long Frozen Referral Identity, Department of Internal Medicine and Clinical Correlation';long.investigations[0].interpretation_template='Long deterministic clinical interpretation. '.repeat(28);const boundary=clone(baseSnapshot);boundary.investigations[0].results=Array.from({length:23},(_,i)=>result(i));const missingSignature=clone(baseSnapshot);missingSignature.signatories.performed_by.signature_data_url=null;missingSignature.signatories.authorized_by.signature_data_url='https://mutable.example/signature.png';return{simple,multi,cbc:simple,profile,abnormal,calculated,amended,nepali,mixed,signatures:simple,long,boundary,missingSignature}}
