import test from'node:test';import assert from'node:assert/strict';
class Queue{constructor(){this.mode='WindowsGateway';this.rows=new Map()}seed(id,type='PaymentConfirmation'){this.rows.set(id,{id,type,status:'Pending',retry:0,max:3,lease:null,started:false,artifactReady:type!=='ReportReady',sent:0})}switch(mode){if([...this.rows.values()].some(x=>x.status==='Processing'))throw Error('INFLIGHT');this.mode=mode}claim(dispatcher,id='x'){const q=this.rows.get(id);if(this.mode!==dispatcher||!q||q.status!=='Pending'||!q.artifactReady)return null;q.status='Processing';q.lease=crypto.randomUUID();return{...q}}begin(id,lease){const q=this.rows.get(id);if(q.status!=='Processing'||q.lease!==lease||q.started)return false;q.started=true;return true}complete(id,lease,outcome){const q=this.rows.get(id);if(q.status==='Sent')return'AlreadySent';if(q.lease!==lease)throw Error('LEASE');if(outcome==='sent'){q.status='Sent';q.sent++;return'Sent'}q.retry++;q.status=outcome==='permanent'||q.retry>=q.max?'DeadLetter':'Pending';q.lease=null;q.started=false;return q.status}stale(id){const q=this.rows.get(id);q.retry++;q.status=q.started?'DeadLetter':'Pending';q.lease=null;q.started=false;return q.status}}
test('single and concurrent claim produce one owner',async()=>{const q=new Queue;q.seed('x');q.switch('CloudflareWorker');const [a,b]=await Promise.all([Promise.resolve().then(()=>q.claim('CloudflareWorker')),Promise.resolve().then(()=>q.claim('CloudflareWorker'))]);assert.equal([a,b].filter(Boolean).length,1)});
test('dispatcher race and mode switch fail closed',()=>{const q=new Queue;q.seed('x');assert(q.claim('WindowsGateway'));assert.equal(q.claim('CloudflareWorker'),null);assert.throws(()=>q.switch('CloudflareWorker'),/INFLIGHT/)});
test('duplicate queue delivery crosses one begin barrier',()=>{const q=new Queue;q.seed('x');q.switch('CloudflareWorker');const a=q.claim('CloudflareWorker');assert(q.begin('x',a.lease));assert.equal(q.begin('x',a.lease),false);assert.equal(q.complete('x',a.lease,'sent'),'Sent');assert.equal(q.rows.get('x').sent,1)});
test('pre-provider stale lease retries; post-provider stale lease deadletters',()=>{const a=new Queue;a.seed('x');assert.equal(a.stale('x'),'Pending');const b=new Queue;b.seed('x');b.rows.get('x').status='Processing';b.rows.get('x').started=true;assert.equal(b.stale('x'),'DeadLetter')});
test('timeouts and 5xx retry, permanent 4xx deadletters, exhaustion deadletters',()=>{const q=new Queue;q.seed('x');let a=q.claim('WindowsGateway');assert.equal(q.complete('x',a.lease,'timeout'),'Pending');a=q.claim('WindowsGateway');assert.equal(q.complete('x',a.lease,'5xx'),'Pending');a=q.claim('WindowsGateway');assert.equal(q.complete('x',a.lease,'5xx'),'DeadLetter');const p=new Queue;p.seed('x');a=p.claim('WindowsGateway');assert.equal(p.complete('x',a.lease,'permanent'),'DeadLetter')});
test('restart recovery and completed replay never duplicate send',()=>{const q=new Queue;q.seed('x');const a=q.claim('WindowsGateway');q.begin('x',a.lease);q.complete('x',a.lease,'sent');assert.equal(q.complete('x',a.lease,'sent'),'AlreadySent');assert.equal(q.rows.get('x').sent,1)});
test('ReportReady waits for artifact; Payment Confirmation does not',()=>{const q=new Queue;q.seed('r','ReportReady');q.seed('p','PaymentConfirmation');assert.equal(q.claim('WindowsGateway','r'),null);assert(q.claim('WindowsGateway','p'));q.rows.get('r').artifactReady=true;assert(q.claim('WindowsGateway','r'))});
