# MOL (0001-0083), GEN (0001-0031), TOX (0001-0049), SPC (0001-0030), PRO (0001-0025), POC (0001-0012)
mol_data = """MOL-0001,Molecular Diagnostics,Infectious Molecular,SARS-CoV-2 RT-PCR,,Single,Respiratory swab,Molecular collection tube / sterile container,RT-PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0002,Molecular Diagnostics,Infectious Molecular,Influenza A PCR,,Single,Respiratory swab,Molecular collection tube / sterile container,RT-PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0003,Molecular Diagnostics,Infectious Molecular,Influenza B PCR,,Single,Respiratory swab,Molecular collection tube / sterile container,RT-PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0004,Molecular Diagnostics,Infectious Molecular,RSV PCR,,Single,Respiratory swab,Molecular collection tube / sterile container,RT-PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0005,Molecular Diagnostics,Infectious Molecular,HBV DNA Quantitative,,Single,EDTA Plasma,Molecular collection tube / sterile container,Real-time PCR,IU/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0006,Molecular Diagnostics,Infectious Molecular,HCV RNA Quantitative,,Single,EDTA Plasma,Molecular collection tube / sterile container,Real-time RT-PCR,IU/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0007,Molecular Diagnostics,Infectious Molecular,HIV-1 RNA Viral Load,,Single,EDTA Plasma,Molecular collection tube / sterile container,Real-time RT-PCR,copies/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0008,Molecular Diagnostics,Infectious Molecular,CMV DNA Quantitative,,Single,EDTA Plasma/Whole Blood,Molecular collection tube / sterile container,Real-time PCR,IU/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0009,Molecular Diagnostics,Infectious Molecular,EBV DNA Quantitative,,Single,EDTA Whole Blood/Plasma,Molecular collection tube / sterile container,Real-time PCR,copies/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0010,Molecular Diagnostics,Infectious Molecular,BK Virus DNA Quantitative,,Single,Plasma/Urine,Molecular collection tube / sterile container,Real-time PCR,copies/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0011,Molecular Diagnostics,Infectious Molecular,JC Virus DNA PCR,,Single,CSF/Plasma,Molecular collection tube / sterile container,PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0012,Molecular Diagnostics,Infectious Molecular,HSV-1/2 DNA PCR,,Single,CSF/Lesion swab,Molecular collection tube / sterile container,PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0013,Molecular Diagnostics,Infectious Molecular,VZV DNA PCR,,Single,CSF/Lesion swab,Molecular collection tube / sterile container,PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0014,Molecular Diagnostics,Infectious Molecular,HPV DNA High Risk,,Single,Cervical specimen,Molecular collection tube / sterile container,PCR/Hybrid capture,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0015,Molecular Diagnostics,Infectious Molecular,HPV Genotyping,,Single,Cervical specimen,Molecular collection tube / sterile container,PCR,Genotype,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0016,Molecular Diagnostics,Infectious Molecular,Chlamydia trachomatis NAAT,,Single,Urine/Swab,Molecular collection tube / sterile container,NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0017,Molecular Diagnostics,Infectious Molecular,Neisseria gonorrhoeae NAAT,,Single,Urine/Swab,Molecular collection tube / sterile container,NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0018,Molecular Diagnostics,Infectious Molecular,Trichomonas vaginalis NAAT,,Single,Urine/Swab,Molecular collection tube / sterile container,NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0019,Molecular Diagnostics,Infectious Molecular,Mycoplasma genitalium NAAT,,Single,Urine/Swab,Molecular collection tube / sterile container,NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0020,Molecular Diagnostics,Infectious Molecular,TB MTB/RIF Molecular Test,,Single,Sputum/Clinical specimen,Molecular collection tube / sterile container,Cartridge NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0021,Molecular Diagnostics,Infectious Molecular,MTB PCR,,Single,Clinical specimen,Molecular collection tube / sterile container,Real-time PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0022,Molecular Diagnostics,Infectious Molecular,TB Drug Resistance Molecular Panel,,Single,Sputum/Culture isolate,Molecular collection tube / sterile container,Line probe/PCR,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0023,Molecular Diagnostics,Infectious Molecular,Malaria PCR,,Single,Whole Blood,Molecular collection tube / sterile container,PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0024,Molecular Diagnostics,Infectious Molecular,Dengue RT-PCR,,Single,Serum,Molecular collection tube / sterile container,RT-PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0025,Molecular Diagnostics,Infectious Molecular,Chikungunya RT-PCR,,Single,Serum,Molecular collection tube / sterile container,RT-PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0026,Molecular Diagnostics,Infectious Molecular,Scrub Typhus PCR,,Single,Whole Blood,Molecular collection tube / sterile container,PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0027,Molecular Diagnostics,Infectious Molecular,Leptospira PCR,,Single,Whole Blood/Urine,Molecular collection tube / sterile container,PCR,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0028,Molecular Diagnostics,Oncology Molecular,BCR-ABL1 Quantitative PCR,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,RT-qPCR,% IS,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0029,Molecular Diagnostics,Oncology Molecular,JAK2 V617F Mutation,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,PCR,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0030,Molecular Diagnostics,Oncology Molecular,JAK2 Exon 12 Mutation,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,PCR/Sequencing,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0031,Molecular Diagnostics,Oncology Molecular,CALR Mutation,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,PCR/Sequencing,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0032,Molecular Diagnostics,Oncology Molecular,MPL Mutation,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,PCR/Sequencing,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0033,Molecular Diagnostics,Oncology Molecular,FLT3 ITD/TKD,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,PCR,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0034,Molecular Diagnostics,Oncology Molecular,NPM1 Mutation,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,PCR,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0035,Molecular Diagnostics,Oncology Molecular,PML-RARA Fusion,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,RT-PCR,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0036,Molecular Diagnostics,Oncology Molecular,RUNX1-RUNX1T1 Fusion,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,RT-PCR,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0037,Molecular Diagnostics,Oncology Molecular,CBFB-MYH11 Fusion,,Single,EDTA Blood/Bone Marrow,EDTA / FFPE block as specified,RT-PCR,Detected/Not detected,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0038,Molecular Diagnostics,Oncology Molecular,EGFR Mutation Panel,,Single,FFPE tissue/Plasma,EDTA / FFPE block as specified,PCR/NGS,Variant report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0039,Molecular Diagnostics,Oncology Molecular,KRAS Mutation,,Single,FFPE tissue/Plasma,EDTA / FFPE block as specified,PCR/NGS,Variant report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0040,Molecular Diagnostics,Oncology Molecular,NRAS Mutation,,Single,FFPE tissue,EDTA / FFPE block as specified,PCR/NGS,Variant report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0041,Molecular Diagnostics,Oncology Molecular,BRAF V600 Mutation,,Single,FFPE tissue/Plasma,EDTA / FFPE block as specified,PCR/NGS,Variant report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0042,Molecular Diagnostics,Oncology Molecular,PIK3CA Mutation,,Single,FFPE tissue,EDTA / FFPE block as specified,PCR/NGS,Variant report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0043,Molecular Diagnostics,Oncology Molecular,ALK Rearrangement,,Single,FFPE tissue,EDTA / FFPE block as specified,FISH/NGS,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0044,Molecular Diagnostics,Oncology Molecular,ROS1 Rearrangement,,Single,FFPE tissue,EDTA / FFPE block as specified,FISH/NGS,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0045,Molecular Diagnostics,Oncology Molecular,RET Rearrangement,,Single,FFPE tissue,EDTA / FFPE block as specified,FISH/NGS,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0046,Molecular Diagnostics,Oncology Molecular,NTRK Fusion,,Single,FFPE tissue,EDTA / FFPE block as specified,NGS,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0047,Molecular Diagnostics,Oncology Molecular,HER2 Amplification by ISH,,Single,FFPE tissue,EDTA / FFPE block as specified,FISH/SISH,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0048,Molecular Diagnostics,Oncology Molecular,MSI Testing,,Single,FFPE tissue,EDTA / FFPE block as specified,PCR/NGS,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0049,Molecular Diagnostics,Oncology Molecular,Tumor Mutational Burden,,Single,FFPE tissue,EDTA / FFPE block as specified,NGS,mut/Mb,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0050,Molecular Diagnostics,Oncology Molecular,BRCA1/BRCA2 Germline,,Single,EDTA Blood,EDTA / FFPE block as specified,NGS,Variant report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0051,Molecular Diagnostics,Oncology Molecular,BRCA1/BRCA2 Somatic,,Single,FFPE tissue,EDTA / FFPE block as specified,NGS,Variant report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0052,Molecular Diagnostics,Oncology Molecular,MLH1 Promoter Methylation,,Single,FFPE tissue,EDTA / FFPE block as specified,Methylation PCR,Interpretive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-15 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0053,Molecular Diagnostics,Infectious Molecular,Norovirus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0054,Molecular Diagnostics,Infectious Molecular,Rotavirus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0055,Molecular Diagnostics,Infectious Molecular,Adenovirus PCR - Stool,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0056,Molecular Diagnostics,Infectious Molecular,Enteric Bacterial PCR Panel,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0057,Molecular Diagnostics,Infectious Molecular,GI Pathogen Multiplex PCR Panel,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0058,Molecular Diagnostics,Infectious Molecular,Meningitis/Encephalitis Multiplex PCR Panel,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0059,Molecular Diagnostics,Infectious Molecular,Respiratory Pathogen Multiplex PCR Panel,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0060,Molecular Diagnostics,Infectious Molecular,Pneumocystis jirovecii PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0061,Molecular Diagnostics,Infectious Molecular,Aspergillus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0062,Molecular Diagnostics,Infectious Molecular,Candida Species PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0063,Molecular Diagnostics,Infectious Molecular,Cryptococcus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0064,Molecular Diagnostics,Infectious Molecular,Toxoplasma gondii PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0065,Molecular Diagnostics,Infectious Molecular,Parvovirus B19 PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0066,Molecular Diagnostics,Infectious Molecular,HHV-6 DNA PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0067,Molecular Diagnostics,Infectious Molecular,HHV-8 DNA PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0068,Molecular Diagnostics,Infectious Molecular,Enterovirus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0069,Molecular Diagnostics,Infectious Molecular,Parechovirus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0070,Molecular Diagnostics,Infectious Molecular,West Nile Virus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0071,Molecular Diagnostics,Infectious Molecular,Japanese Encephalitis Virus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0072,Molecular Diagnostics,Infectious Molecular,Zika Virus RT-PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0073,Molecular Diagnostics,Infectious Molecular,Mpox (Monkeypox) PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0074,Molecular Diagnostics,Infectious Molecular,Bordetella pertussis PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0075,Molecular Diagnostics,Infectious Molecular,Legionella pneumophila PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0076,Molecular Diagnostics,Infectious Molecular,Streptococcus pneumoniae PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0077,Molecular Diagnostics,Infectious Molecular,Haemophilus influenzae PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0078,Molecular Diagnostics,Infectious Molecular,Mycoplasma pneumoniae PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0079,Molecular Diagnostics,Infectious Molecular,Chlamydophila pneumoniae PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0080,Molecular Diagnostics,Infectious Molecular,MRSA PCR Screen,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0081,Molecular Diagnostics,Infectious Molecular,Clostridioides difficile Toxin Gene PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0082,Molecular Diagnostics,Infectious Molecular,Group B Streptococcus PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,
MOL-0083,Molecular Diagnostics,Infectious Molecular,Candida auris PCR,,Single,Clinical specimen as specified,Molecular collection tube / sterile container,PCR/RT-PCR/Multiplex NAAT,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Same day-3 days,DetectedNotDetected,No,No,Yes,,REQUIRES LAB VALIDATION,"""

gen_data = """GEN-0001,Genetics / Cytogenetics,Genetic Testing,Conventional Karyotyping - Peripheral Blood,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0002,Genetics / Cytogenetics,Genetic Testing,Conventional Karyotyping - Bone Marrow,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0003,Genetics / Cytogenetics,Genetic Testing,FISH - BCR/ABL1,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0004,Genetics / Cytogenetics,Genetic Testing,FISH - PML/RARA,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0005,Genetics / Cytogenetics,Genetic Testing,FISH - HER2,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0006,Genetics / Cytogenetics,Genetic Testing,FISH - ALK,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0007,Genetics / Cytogenetics,Genetic Testing,FISH - ROS1,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0008,Genetics / Cytogenetics,Genetic Testing,FISH - 1p/19q Codeletion,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0009,Genetics / Cytogenetics,Genetic Testing,FISH - MYC,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0010,Genetics / Cytogenetics,Genetic Testing,FISH - BCL2,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0011,Genetics / Cytogenetics,Genetic Testing,FISH - BCL6,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0012,Genetics / Cytogenetics,Genetic Testing,FISH - EWSR1,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0013,Genetics / Cytogenetics,Genetic Testing,FISH - SS18,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0014,Genetics / Cytogenetics,Genetic Testing,FISH - MDM2,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0015,Genetics / Cytogenetics,Genetic Testing,FISH - DDIT3,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0016,Genetics / Cytogenetics,Genetic Testing,FISH - RET,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0017,Genetics / Cytogenetics,Genetic Testing,FISH - NTRK,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0018,Genetics / Cytogenetics,Genetic Testing,Chromosomal Microarray,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0019,Genetics / Cytogenetics,Genetic Testing,Whole Exome Sequencing,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0020,Genetics / Cytogenetics,Genetic Testing,Targeted Clinical Exome,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0021,Genetics / Cytogenetics,Genetic Testing,Carrier Screening Panel,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0022,Genetics / Cytogenetics,Genetic Testing,Thalassemia Mutation Analysis,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0023,Genetics / Cytogenetics,Genetic Testing,HFE Hemochromatosis Mutation,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0024,Genetics / Cytogenetics,Genetic Testing,Factor V Leiden Mutation,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0025,Genetics / Cytogenetics,Genetic Testing,Prothrombin G20210A Mutation,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0026,Genetics / Cytogenetics,Genetic Testing,MTHFR C677T/A1298C,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0027,Genetics / Cytogenetics,Genetic Testing,HLA-B27 Genotyping,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0028,Genetics / Cytogenetics,Genetic Testing,HLA-B*57:01,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0029,Genetics / Cytogenetics,Genetic Testing,HLA-B*15:02,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0030,Genetics / Cytogenetics,Genetic Testing,HLA Typing Class I,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
GEN-0031,Genetics / Cytogenetics,Genetic Testing,HLA Typing Class II,,Single,EDTA Blood / Bone Marrow / FFPE as applicable,EDTA / Heparin / FFPE,Karyotype/FISH/PCR/NGS as applicable,Descriptive,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,5-21 days,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,"""

tox_data = """TOX-0001,Toxicology / TDM,Therapeutic Drug Monitoring,Lithium,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,mmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0002,Toxicology / TDM,Therapeutic Drug Monitoring,Valproic Acid,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0003,Toxicology / TDM,Therapeutic Drug Monitoring,Carbamazepine,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0004,Toxicology / TDM,Therapeutic Drug Monitoring,"Phenytoin, Total",,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0005,Toxicology / TDM,Therapeutic Drug Monitoring,"Phenytoin, Free",,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0006,Toxicology / TDM,Therapeutic Drug Monitoring,Phenobarbital,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0007,Toxicology / TDM,Therapeutic Drug Monitoring,Digoxin,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,ng/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0008,Toxicology / TDM,Therapeutic Drug Monitoring,Theophylline,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0009,Toxicology / TDM,Therapeutic Drug Monitoring,Vancomycin Trough,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0010,Toxicology / TDM,Therapeutic Drug Monitoring,Vancomycin Peak,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0011,Toxicology / TDM,Therapeutic Drug Monitoring,Gentamicin Trough,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0012,Toxicology / TDM,Therapeutic Drug Monitoring,Gentamicin Peak,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0013,Toxicology / TDM,Therapeutic Drug Monitoring,Amikacin Trough,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0014,Toxicology / TDM,Therapeutic Drug Monitoring,Amikacin Peak,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0015,Toxicology / TDM,Therapeutic Drug Monitoring,Tacrolimus,,Single,EDTA Whole Blood,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,ng/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0016,Toxicology / TDM,Therapeutic Drug Monitoring,Cyclosporine,,Single,EDTA Whole Blood,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,ng/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0017,Toxicology / TDM,Therapeutic Drug Monitoring,Sirolimus,,Single,EDTA Whole Blood,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,ng/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0018,Toxicology / TDM,Therapeutic Drug Monitoring,Everolimus,,Single,EDTA Whole Blood,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,ng/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0019,Toxicology / TDM,Therapeutic Drug Monitoring,Methotrexate,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0020,Toxicology / TDM,Therapeutic Drug Monitoring,Acetaminophen / Paracetamol,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,µg/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0021,Toxicology / TDM,Therapeutic Drug Monitoring,Salicylate,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,mg/dL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0022,Toxicology / TDM,Therapeutic Drug Monitoring,Ethanol,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,mg/dL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0023,Toxicology / TDM,Therapeutic Drug Monitoring,Methanol,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,mg/dL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0024,Toxicology / TDM,Therapeutic Drug Monitoring,Ethylene Glycol,,Single,Serum/Plasma,EDTA / Plain as specified,Immunoassay/Chromatography/LC-MS,mg/dL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,Collection timing relative to dose must be configured.
TOX-0025,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Amphetamine,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0026,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Methamphetamine,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0027,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Cocaine Metabolite,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0028,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Opiates,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0029,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Morphine,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0030,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Heroin/6-MAM,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0031,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Cannabinoids/THC,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0032,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Benzodiazepines,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0033,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Barbiturates,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0034,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Methadone,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0035,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Buprenorphine,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0036,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Tramadol,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0037,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Fentanyl,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0038,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Phencyclidine (PCP),,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0039,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Tricyclic Antidepressants,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0040,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - Ketamine,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0041,Toxicology / TDM,Drugs of Abuse,Urine Drug Screen - MDMA/Ecstasy,,Single,Urine,Urine container,Immunoassay screen; confirm by GC-MS/LC-MS if required,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0042,Toxicology / TDM,Heavy Metals,"Lead, Blood",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/dL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0043,Toxicology / TDM,Heavy Metals,"Mercury, Blood",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0044,Toxicology / TDM,Heavy Metals,"Mercury, Urine",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0045,Toxicology / TDM,Heavy Metals,"Arsenic, Blood",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0046,Toxicology / TDM,Heavy Metals,"Arsenic, Urine",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0047,Toxicology / TDM,Heavy Metals,"Cadmium, Blood",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0048,Toxicology / TDM,Heavy Metals,"Cadmium, Urine",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
TOX-0049,Toxicology / TDM,Heavy Metals,"Aluminium, Serum",,Single,Blood/Urine as specified,Trace element tube / urine container,ICP-MS/AAS,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,"""

spc_data = """SPC-0001,Special Chemistry,Metabolic / Screening,Neonatal TSH Screen,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,µIU/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0002,Special Chemistry,Metabolic / Screening,Neonatal 17-OHP Screen,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,ng/mL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0003,Special Chemistry,Metabolic / Screening,Neonatal G6PD Screen,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0004,Special Chemistry,Metabolic / Screening,"Phenylalanine, Dried Blood Spot",,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,µmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0005,Special Chemistry,Metabolic / Screening,"Amino Acid Profile, Plasma",,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0006,Special Chemistry,Metabolic / Screening,Acylcarnitine Profile,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0007,Special Chemistry,Metabolic / Screening,"Organic Acids, Urine",,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0008,Special Chemistry,Metabolic / Screening,Galactosemia Screen,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Qualitative,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PositiveNegative,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0009,Special Chemistry,Metabolic / Screening,Biotinidase Activity,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,U/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0010,Special Chemistry,Metabolic / Screening,Sweat Chloride,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,mmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0011,Special Chemistry,Metabolic / Screening,Alpha-Fetoprotein Maternal Serum,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,MoM,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0012,Special Chemistry,Metabolic / Screening,PAPP-A,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,MoM,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0013,Special Chemistry,Metabolic / Screening,"Free Beta-hCG, First Trimester",,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,MoM,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0014,Special Chemistry,Metabolic / Screening,Quadruple Marker Screen,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Risk report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0015,Special Chemistry,Metabolic / Screening,Dual Marker Screen,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Risk report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0016,Special Chemistry,Metabolic / Screening,Triple Marker Screen,,Single,Blood/DBS/Urine/Sweat as specified,Appropriate collection device,Validated screening/LC-MS/MS method,Risk report,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,PathologyNarrative,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0017,Special Chemistry,Vitamins / Trace Elements,"Selenium, Serum",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0018,Special Chemistry,Vitamins / Trace Elements,"Manganese, Whole Blood",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0019,Special Chemistry,Vitamins / Trace Elements,"Chromium, Blood",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0020,Special Chemistry,Vitamins / Trace Elements,"Cobalt, Blood",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0021,Special Chemistry,Vitamins / Trace Elements,"Nickel, Blood",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0022,Special Chemistry,Vitamins / Trace Elements,"Iodine, Urine",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0023,Special Chemistry,Vitamins / Trace Elements,"Iodine, Serum",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0024,Special Chemistry,Vitamins / Trace Elements,"Molybdenum, Blood",,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0025,Special Chemistry,Vitamins / Trace Elements,Vitamin A (Retinol),,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,µg/dL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0026,Special Chemistry,Vitamins / Trace Elements,Vitamin E (Alpha-Tocopherol),,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,mg/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0027,Special Chemistry,Vitamins / Trace Elements,Vitamin B1 (Thiamine),,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,nmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0028,Special Chemistry,Vitamins / Trace Elements,Vitamin B6 (PLP),,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,nmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0029,Special Chemistry,Vitamins / Trace Elements,Vitamin C,,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,mg/dL,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
SPC-0030,Special Chemistry,Vitamins / Trace Elements,Methylmalonic Acid,,Single,Serum/Whole Blood/Urine as specified,Trace element / Plain tube,LC-MS/MS/HPLC/ICP-MS as validated,nmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,"""

pro_data = """PRO-0001,Profiles / Packages,Clinical Profiles,Liver Function Test (LFT),,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Total Bilirubin; Direct Bilirubin; AST (SGOT); ALT (SGPT); Alkaline Phosphatase (ALP); GGT; Total Protein; Albumin
PRO-0002,Profiles / Packages,Clinical Profiles,Renal Function Test (RFT/KFT),,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Urea; Creatinine; Uric Acid; Sodium; Potassium; Chloride
PRO-0003,Profiles / Packages,Clinical Profiles,Lipid Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Total Cholesterol; Triglycerides; HDL Cholesterol; LDL Cholesterol, Calculated; VLDL Cholesterol; Non-HDL Cholesterol"
PRO-0004,Profiles / Packages,Clinical Profiles,Thyroid Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: TSH; Free T4 (FT4); Free T3 (FT3)
PRO-0005,Profiles / Packages,Clinical Profiles,Iron Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Iron; TIBC; UIBC; Transferrin Saturation; Ferritin
PRO-0006,Profiles / Packages,Clinical Profiles,Diabetes Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Glucose, Fasting; Glucose, Postprandial 2 hr; HbA1c"
PRO-0007,Profiles / Packages,Clinical Profiles,Cardiac Marker Panel,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Troponin I, High Sensitivity; CK-MB Mass; Myoglobin"
PRO-0008,Profiles / Packages,Clinical Profiles,Electrolyte Panel,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Sodium; Potassium; Chloride; Bicarbonate / Total CO2
PRO-0009,Profiles / Packages,Clinical Profiles,Bone Mineral Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Calcium, Total; Phosphorus; Alkaline Phosphatase (ALP); Vitamin D, 25-OH; PTH, Intact"
PRO-0010,Profiles / Packages,Clinical Profiles,Fertility Female Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: FSH; LH; Estradiol (E2); Prolactin; TSH; AMH
PRO-0011,Profiles / Packages,Clinical Profiles,Fertility Male Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Testosterone, Total; FSH; LH; Prolactin"
PRO-0012,Profiles / Packages,Clinical Profiles,PCOS Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: LH; FSH; Testosterone, Total; DHEA-S; 17-OH Progesterone; TSH; Prolactin; Insulin, Fasting"
PRO-0013,Profiles / Packages,Clinical Profiles,Anemia Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Complete Blood Count (CBC); Reticulocyte Count; Ferritin; Iron; TIBC; Vitamin B12; Folate
PRO-0014,Profiles / Packages,Clinical Profiles,Coagulation Screen,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Prothrombin Time (PT); INR; Activated Partial Thromboplastin Time (APTT)
PRO-0015,Profiles / Packages,Clinical Profiles,Thrombophilia Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Protein C Activity; Protein S Activity; Antithrombin III Activity; Lupus Anticoagulant Screen; Factor V Leiden Mutation; Prothrombin G20210A Mutation
PRO-0016,Profiles / Packages,Clinical Profiles,TORCH Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Toxoplasma IgM; Toxoplasma IgG; Rubella IgM; Rubella IgG; CMV IgM; CMV IgG; HSV-1 IgG; HSV-2 IgG
PRO-0017,Profiles / Packages,Clinical Profiles,Hepatitis B Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: HBsAg; Anti-HBs; Anti-HBc Total; Anti-HBc IgM; HBeAg; Anti-HBe
PRO-0018,Profiles / Packages,Clinical Profiles,Autoimmune Screen,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: ANA by IFA; Anti-dsDNA; C3 Complement; C4 Complement
PRO-0019,Profiles / Packages,Clinical Profiles,Rheumatology Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Rheumatoid Factor (RF); Anti-CCP; CRP, Quantitative; ESR (Westergren)"
PRO-0020,Profiles / Packages,Clinical Profiles,Multiple Myeloma Screen,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Serum Protein Electrophoresis; Immunofixation Electrophoresis, Serum; Free Kappa Light Chain; Free Lambda Light Chain; Kappa/Lambda Ratio; Beta-2 Microglobulin"
PRO-0021,Profiles / Packages,Clinical Profiles,Antenatal Basic Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Complete Blood Count (CBC); Blood Group ABO; Rh(D) Typing; Glucose, Random; HBsAg; HIV 1/2 Ag/Ab 4th Generation; RPR; Urine Routine Examination (RE/ME)"
PRO-0022,Profiles / Packages,Clinical Profiles,Preoperative Basic Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Complete Blood Count (CBC); Prothrombin Time (PT); INR; Creatinine; Glucose, Random; Blood Group ABO; Rh(D) Typing"
PRO-0023,Profiles / Packages,Clinical Profiles,Fever Panel - Basic,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Complete Blood Count (CBC); CRP, Quantitative; Dengue NS1 Antigen; Malaria Pf/Pv Antigen; Scrub Typhus IgM"
PRO-0024,Profiles / Packages,Clinical Profiles,Hypertension Secondary Screen,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,Components: Sodium; Potassium; Creatinine; Aldosterone; Direct Renin; Aldosterone/Renin Ratio
PRO-0025,Profiles / Packages,Clinical Profiles,Pituitary Profile,,Panel,Multiple specimens as applicable,As required,Composite panel,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,"Components: Prolactin; FSH; LH; TSH; Free T4 (FT4); Cortisol, 8 AM; IGF-1"
"""

poc_data = """POC-0001,Point of Care / Blood Gas,Blood Gas,Arterial Blood Gas (ABG),,Panel,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0002,Point of Care / Blood Gas,Blood Gas,Venous Blood Gas (VBG),,Panel,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,Panel,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Panel,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0003,Point of Care / Blood Gas,Blood Gas,"pH, Blood Gas",,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,pH,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0004,Point of Care / Blood Gas,Blood Gas,"pCO2, Blood Gas",,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,mmHg,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0005,Point of Care / Blood Gas,Blood Gas,"pO2, Blood Gas",,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,mmHg,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0006,Point of Care / Blood Gas,Blood Gas,"HCO3-, Blood Gas",,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,mmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Calculated,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0007,Point of Care / Blood Gas,Blood Gas,Base Excess,,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,mmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Calculated,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0008,Point of Care / Blood Gas,Blood Gas,"Oxygen Saturation, Blood Gas",,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,%,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0009,Point of Care / Blood Gas,Blood Gas,"Lactate, Blood Gas",,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,mmol/L,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0010,Point of Care / Blood Gas,Blood Gas,Carboxyhemoglobin,,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,%,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0011,Point of Care / Blood Gas,Blood Gas,Methemoglobin,,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,%,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,
POC-0012,Point of Care / Blood Gas,Blood Gas,Oxyhemoglobin,,Single,Heparinized arterial/venous whole blood,Heparinized blood gas syringe,Blood gas analyzer,%,VALIDATE PER METHOD/AGE/SEX,CONFIGURE PER LAB POLICY,Routine,Numeric,No,No,Yes,,REQUIRES LAB VALIDATION,"""
