\set ON_ERROR_STOP on
BEGIN;
CREATE TEMP TABLE acceptance_results(test_no INT PRIMARY KEY,name TEXT,passed BOOLEAN);
GRANT ALL ON acceptance_results TO authenticated,anon;
CREATE OR REPLACE FUNCTION pg_temp.ok(n INT,name TEXT,condition BOOLEAN) RETURNS VOID LANGUAGE plpgsql AS $$BEGIN IF NOT COALESCE(condition,FALSE) THEN RAISE EXCEPTION 'TEST_%_FAILED: %',n,name;END IF;INSERT INTO acceptance_results VALUES(n,name,TRUE);RAISE NOTICE 'PASS %: %',n,name;END$$;

INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES
('97000000-0000-0000-0000-000000000001','owner@runtime.invalid','{"full_name":"Runtime Owner"}'),
('97000000-0000-0000-0000-000000000002','tech@runtime.invalid','{"full_name":"Runtime Technician"}'),
('97000000-0000-0000-0000-000000000003','inactive@runtime.invalid','{"full_name":"Runtime Inactive"}'),
('97000000-0000-0000-0000-000000000004','gateway@runtime.invalid','{"full_name":"Runtime Gateway"}'),
('97000000-0000-0000-0000-000000000005','worker@runtime.invalid','{"full_name":"Runtime Worker"}');
UPDATE public.user_profiles SET is_active=id IN('97000000-0000-0000-0000-000000000001','97000000-0000-0000-0000-000000000002'),is_super_admin=id='97000000-0000-0000-0000-000000000001' WHERE id::TEXT LIKE '97000000-%';
INSERT INTO public.user_roles(user_id,role_id)VALUES('97000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000004');
INSERT INTO public.reporting_personnel(id,user_id,full_name,professional_type,qualification,registration_council,registration_number,can_enter_results,can_verify_results,can_acknowledge_critical,can_sign_reports,is_active,display_order)
VALUES('97100000-0000-0000-0000-000000000001','97000000-0000-0000-0000-000000000002','Runtime Technician','Lab Technologist','BMLT','Runtime Council','RT-1',TRUE,TRUE,TRUE,TRUE,TRUE,999);

SET LOCAL ROLE authenticated;SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000001',TRUE);
SELECT pg_temp.ok(1,'Super Admin can perform all app operations',public.is_super_admin() AND public.has_permission('can_manage_users') AND public.has_permission('can_manage_catalogue'));
SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000002',TRUE);
SELECT pg_temp.ok(2,'Lab Technician operational access',(SELECT bool_and(public.has_permission(p)) FROM unnest(ARRAY['can_view_dashboard','can_create_bill','can_edit_patient','can_collect_sample','can_receive_sample','can_reject_sample','can_enter_results','can_verify_results','can_acknowledge_critical','can_sign_reports','can_amend_reports','can_print_reports','can_manage_catalogue','can_manage_ast_breakpoints','can_manage_referring_doctors','can_manage_personnel','can_view_financials','can_view_audit_logs','can_manage_outsource_tracking','can_view_hmis_reports','can_edit_hmis_reports','can_finalize_hmis_reports'])p));
SELECT pg_temp.ok(3,'normal assignment only Lab Technician',(SELECT count(*)=1 FROM public.roles WHERE code='lab_technician' AND description LIKE 'System-defined%'));
SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000001',TRUE);
DO $$BEGIN BEGIN PERFORM public.update_user_access('97000000-0000-0000-0000-000000000003',TRUE,FALSE,ARRAY['00000000-0000-0000-0000-000000000001']::UUID[]);RAISE EXCEPTION 'admin accepted';EXCEPTION WHEN SQLSTATE '22023' THEN PERFORM pg_temp.ok(4,'Administrator assignment denied/compatibility-only',TRUE);END;END$$;
DO $$BEGIN BEGIN PERFORM public.update_user_access('97000000-0000-0000-0000-000000000003',TRUE,FALSE,ARRAY['00000000-0000-0000-0000-000000000002']::UUID[]);RAISE EXCEPTION 'verifier accepted';EXCEPTION WHEN SQLSTATE '22023' THEN PERFORM pg_temp.ok(5,'Verifier assignment denied',TRUE);END;END$$;
DO $$BEGIN BEGIN PERFORM public.update_user_access('97000000-0000-0000-0000-000000000003',TRUE,FALSE,ARRAY['00000000-0000-0000-0000-000000000003']::UUID[]);RAISE EXCEPTION 'signatory accepted';EXCEPTION WHEN SQLSTATE '22023' THEN PERFORM pg_temp.ok(6,'Signatory assignment denied',TRUE);END;END$$;
SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000003',TRUE);SELECT pg_temp.ok(7,'inactive denied',NOT public.has_permission('can_create_bill'));
RESET ROLE;SET LOCAL ROLE anon;SELECT set_config('request.jwt.claim.sub','',TRUE);DO $$BEGIN BEGIN PERFORM public.has_permission('can_create_bill');RAISE EXCEPTION 'anon accepted';EXCEPTION WHEN insufficient_privilege THEN PERFORM pg_temp.ok(8,'anon denied',TRUE);END;END$$;
RESET ROLE;SET LOCAL ROLE authenticated;SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000004',TRUE);SELECT pg_temp.ok(9,'Gateway denied',NOT public.has_permission('can_create_bill'));
SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000005',TRUE);SELECT pg_temp.ok(10,'Worker denied',NOT public.has_permission('can_create_bill'));

SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000002',TRUE);
DO $$DECLARE c UUID;t JSONB;tid UUID;BEGIN c:=public.catalogue_save_category(jsonb_build_object('code','RT_CAT','name','Runtime Category','description','rollback','display_order',999),NULL);t:=public.catalogue_save_test(jsonb_build_object('code','RT_TEST','name','Runtime Test','short_name','RT','description','rollback','category_id',c,'department','Runtime','category','Runtime Category','test_kind','Individual','reporting_type','NoReporting','price_paisa',10000,'sample_type','','container','','tat_hours',1,'display_order',999,'price_configured',TRUE,'allow_zero_price_billing',FALSE,'pricing_policy','Fixed','search_aliases','[]'::JSONB,'clinical_configuration_status','Configured','workflow_supported',TRUE),NULL);tid:=(t->>'id')::UUID;PERFORM set_config('runtime.test_id',tid::TEXT,TRUE);PERFORM set_config('runtime.category_id',c::TEXT,TRUE);PERFORM pg_temp.ok(11,'Technician add test',tid IS NOT NULL);END$$;
SELECT pg_temp.ok(63,'new catalogue test enters readiness workflow',EXISTS(SELECT 1 FROM public.catalogue_readiness_inventory(NULL,'RT_TEST') AS x(value) WHERE x.value->>'test_id'=current_setting('runtime.test_id')));
DO $$DECLARE tid UUID:=current_setting('runtime.test_id')::UUID;v BIGINT;t JSONB;BEGIN SELECT row_version INTO v FROM public.tests WHERE id=tid;t:=public.catalogue_save_test((SELECT to_jsonb(x)||jsonb_build_object('name','Runtime Test Edited','category_id',category_id,'search_aliases','[]'::JSONB) FROM public.tests x WHERE id=tid),v);PERFORM pg_temp.ok(12,'Technician edit test',(SELECT name='Runtime Test Edited' FROM public.tests WHERE id=tid));END$$;
DO $$DECLARE tid UUID:=current_setting('runtime.test_id')::UUID;r JSONB;BEGIN r:=public.catalogue_set_current_rate('Test',tid,12500,NULL,NULL,'runtime update');PERFORM pg_temp.ok(13,'Technician update rate',(r->>'price_paisa')::BIGINT=12500);END$$;
SELECT pg_temp.ok(14,'Technician category CRUD',(SELECT name='Runtime Category' FROM public.test_categories WHERE id=current_setting('runtime.category_id')::UUID));
DO $$DECLARE pid UUID;BEGIN pid:=public.catalogue_save_parameter(jsonb_build_object('test_id',current_setting('runtime.test_id'),'code','RTP','name','Runtime Parameter','value_type','Numeric','unit','mg/dL','display_order',1,'is_mandatory',TRUE,'is_active',TRUE,'decimal_precision',2,'calculation_identifier',NULL,'option_set_id',NULL),NULL);PERFORM set_config('runtime.parameter_id',pid::TEXT,TRUE);PERFORM pg_temp.ok(15,'Technician parameter CRUD',pid IS NOT NULL);END$$;
DO $$DECLARE rid UUID;BEGIN rid:=public.catalogue_save_range(jsonb_build_object('parameter_id',current_setting('runtime.parameter_id'),'gender','All','age_min_days',0,'age_max_days',50000,'normal_min',10,'normal_max',20,'critical_low',5,'critical_high',30,'normal_text',NULL,'method','Runtime','unit','mg/dL'),NULL);PERFORM set_config('runtime.range_id',rid::TEXT,TRUE);PERFORM pg_temp.ok(16,'Technician range CRUD',rid IS NOT NULL);PERFORM pg_temp.ok(17,'Technician critical range',(SELECT critical_low=5 AND critical_high=30 FROM public.reference_ranges WHERE id=rid));END$$;
DO $$DECLARE p UUID;v BIGINT;BEGIN p:=public.catalogue_save_panel(jsonb_build_object('code','RT_PANEL','name','Runtime Panel','category_id',current_setting('runtime.category_id'),'display_order',999),NULL);SELECT row_version INTO v FROM public.catalogue_panels WHERE id=p;PERFORM public.catalogue_save_panel_component(p,current_setting('runtime.test_id')::UUID,NULL,'Runtime Test',1,v);PERFORM set_config('runtime.panel_id',p::TEXT,TRUE);PERFORM pg_temp.ok(18,'Technician panel/profile CRUD',p IS NOT NULL);SELECT row_version INTO v FROM public.catalogue_panels WHERE id=p;PERFORM public.catalogue_reorder_panel_components(p,ARRAY[current_setting('runtime.test_id')::UUID],v);PERFORM pg_temp.ok(19,'Technician membership reorder',TRUE);END$$;
DO $$DECLARE tid UUID:=current_setting('runtime.test_id')::UUID;v BIGINT;s JSONB;BEGIN SELECT row_version INTO v FROM public.tests WHERE id=tid;s:=public.catalogue_set_test_lifecycle(tid,'Active',v);SELECT row_version INTO v FROM public.tests WHERE id=tid;s:=public.catalogue_set_test_lifecycle(tid,'Draft',v);PERFORM pg_temp.ok(20,'Technician activation/deactivation',(s->>'status')='Draft');END$$;
DO $$DECLARE t JSONB;tid UUID;v BIGINT;BEGIN t:=public.catalogue_save_test(jsonb_build_object('code','RT_DELETE','name','Runtime Delete','category_id',current_setting('runtime.category_id'),'department','Runtime','category','Runtime Category','test_kind','Individual','reporting_type','NoReporting','price_paisa',100,'sample_type','','container','','tat_hours',1,'display_order',1000,'price_configured',TRUE,'pricing_policy','Fixed','search_aliases','[]'::JSONB,'clinical_configuration_status','Configured','workflow_supported',TRUE),NULL);tid:=(t->>'id')::UUID;SELECT row_version INTO v FROM public.tests WHERE id=tid;PERFORM public.catalogue_delete_test(tid,v);PERFORM pg_temp.ok(21,'Technician unused delete',NOT EXISTS(SELECT 1 FROM public.tests WHERE id=tid));END$$;
-- Reference the runtime test through a package component, then prove delete denial and archive.
RESET ROLE;
INSERT INTO public.health_packages(id,code,name,price_paisa,lifecycle_status)VALUES('97200000-0000-0000-0000-000000000001','RT_PKG_REF','Runtime Ref Package',100,'Draft');INSERT INTO public.health_package_components(package_id,test_id,display_order)VALUES('97200000-0000-0000-0000-000000000001',current_setting('runtime.test_id')::UUID,1);
SET LOCAL ROLE authenticated;SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000002',TRUE);
DO $$DECLARE v BIGINT;BEGIN SELECT row_version INTO v FROM public.tests WHERE id=current_setting('runtime.test_id')::UUID;BEGIN PERFORM public.catalogue_delete_test(current_setting('runtime.test_id')::UUID,v);RAISE EXCEPTION 'delete accepted';EXCEPTION WHEN foreign_key_violation THEN PERFORM pg_temp.ok(22,'referenced delete denied',TRUE);END;PERFORM public.catalogue_set_test_lifecycle(current_setting('runtime.test_id')::UUID,'Archived',v);PERFORM pg_temp.ok(23,'archive referenced',(SELECT lifecycle_status='Archived' FROM public.tests WHERE id=current_setting('runtime.test_id')::UUID));END$$;
SELECT pg_temp.ok(24,'rate history',(SELECT count(*)>=1 FROM public.catalogue_rate_history('Test',current_setting('runtime.test_id')::UUID,NULL)));
DO $$BEGIN BEGIN PERFORM public.catalogue_set_current_rate('Test',current_setting('runtime.test_id')::UUID,13000,NULL,NULL,'stale');RAISE EXCEPTION 'stale accepted';EXCEPTION WHEN SQLSTATE 'PT409' THEN PERFORM pg_temp.ok(25,'stale rate version conflict',TRUE);END;END$$;
DO $$DECLARE before_count BIGINT;BEGIN SELECT count(*) INTO before_count FROM public.catalogue_rate_versions;BEGIN PERFORM public.catalogue_bulk_set_current_rates(jsonb_build_array(jsonb_build_object('entity_type','Test','entity_id',current_setting('runtime.test_id'),'price_paisa',14000,'expected_rate_id',NULL,'expected_rate_version',NULL,'reason','bulk'),jsonb_build_object('entity_type','Test','entity_id',current_setting('runtime.test_id'),'price_paisa',-1,'reason','invalid')));RAISE EXCEPTION 'bulk accepted';EXCEPTION WHEN OTHERS THEN NULL;END;PERFORM pg_temp.ok(26,'bulk rate atomicity',(SELECT count(*)=before_count FROM public.catalogue_rate_versions));END$$;

-- Flexible billing fixtures: one configured and one unconfigured active test.
RESET ROLE;INSERT INTO public.tests(id,code,name,department,category,reporting_type,price_paisa,sample_type,container,is_active,display_order,allow_manual_price,price_configured,pricing_policy,lifecycle_status,billing_enabled,clinical_reporting_enabled,collection_required,workflow_supported,clinical_configuration_status,category_id)
VALUES('97300000-0000-0000-0000-000000000001','RT_BILL_FIXED','Runtime Billing Fixed','Runtime','Runtime','NoReporting',60000,'','','true',9990,FALSE,TRUE,'Fixed','Active',TRUE,FALSE,FALSE,TRUE,'Configured',current_setting('runtime.category_id')::UUID),
('97300000-0000-0000-0000-000000000002','RT_BILL_OPEN','Runtime Billing Open','Runtime','Runtime','NoReporting',0,'','','true',9991,FALSE,FALSE,'PricePending','Active',TRUE,FALSE,FALSE,TRUE,'Configured',current_setting('runtime.category_id')::UUID);
SET LOCAL ROLE authenticated;SELECT set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000002',TRUE);
CREATE OR REPLACE FUNCTION pg_temp.bill(test_id UUID,rate BIGINT,key TEXT,paid BIGINT DEFAULT 0,discount BIGINT DEFAULT 0)RETURNS JSONB LANGUAGE plpgsql AS $$DECLARE t public.tests%ROWTYPE;BEGIN SELECT * INTO t FROM public.tests WHERE id=test_id;RETURN public.create_patient_bill_order_with_packages(jsonb_build_object('mobile','98'||lpad((abs(hashtext(key))%100000000)::TEXT,8,'0'),'full_name','Runtime Billing Patient','gender','Other','age_years',30,'age_months',0,'age_days',0,'address','Runtime'),jsonb_build_object('gross_amount_paisa',rate,'discount_amount_paisa',discount,'paid_amount_paisa',paid,'order_date_bs','2083-05-15','remarks','runtime'),ARRAY[jsonb_build_object('test_id',t.id,'unit_price_paisa',rate,'manual_price_paisa',rate,'discount_paisa',discount,'zero_price_acknowledged',FALSE)],CASE WHEN paid>0 THEN jsonb_build_object('payment_mode','Cash','received_by_name','Runtime Technician') END,key,'[]');END$$;
DO $$DECLARE r JSONB;BEGIN r:=pg_temp.bill('97300000-0000-0000-0000-000000000001',60000,'rt-default');PERFORM pg_temp.ok(27,'configured default rate',(r->>'gross_amount_paisa')::BIGINT=60000);r:=pg_temp.bill('97300000-0000-0000-0000-000000000001',55000,'rt-lower');PERFORM pg_temp.ok(28,'configured rate edited lower',(r->>'gross_amount_paisa')::BIGINT=55000);r:=pg_temp.bill('97300000-0000-0000-0000-000000000001',65000,'rt-higher');PERFORM pg_temp.ok(29,'configured rate edited higher',(r->>'gross_amount_paisa')::BIGINT=65000);r:=pg_temp.bill('97300000-0000-0000-0000-000000000002',60000,'rt-open');PERFORM pg_temp.ok(30,'unconfigured plus valid agreed rate',(r->>'gross_amount_paisa')::BIGINT=60000);END$$;
DO $$BEGIN BEGIN PERFORM pg_temp.bill('97300000-0000-0000-0000-000000000002',NULL,'rt-missing');RAISE EXCEPTION 'missing accepted';EXCEPTION WHEN OTHERS THEN PERFORM pg_temp.ok(31,'unconfigured missing rate denied',TRUE);END;BEGIN PERFORM pg_temp.bill('97300000-0000-0000-0000-000000000002',0,'rt-zero');RAISE EXCEPTION 'zero accepted';EXCEPTION WHEN OTHERS THEN PERFORM pg_temp.ok(32,'zero rate behavior',TRUE);END;BEGIN PERFORM pg_temp.bill('97300000-0000-0000-0000-000000000002',-1,'rt-negative');RAISE EXCEPTION 'negative accepted';EXCEPTION WHEN OTHERS THEN PERFORM pg_temp.ok(33,'negative rate denied',TRUE);END;END$$;
SELECT pg_temp.ok(34,'panel default rate',EXISTS(SELECT 1 FROM public.catalogue_rate_versions WHERE panel_service_id IS NOT NULL AND status='Active'));
SELECT pg_temp.ok(35,'panel edited agreed rate',pg_get_functiondef('public.create_patient_bill_order_with_panel_service(jsonb,jsonb,jsonb,text,uuid,bigint,bigint)'::regprocedure) LIKE '%p_agreed_panel_price_paisa%');
SELECT pg_temp.ok(36,'migration 00086 panel regression',NOT has_function_privilege('authenticated','public.create_patient_bill_order_with_panel_service(jsonb,jsonb,jsonb,text,uuid,bigint)','EXECUTE'));
DO $$DECLARE a JSONB;b JSONB;BEGIN a:=pg_temp.bill('97300000-0000-0000-0000-000000000001',61000,'rt-mixed-a');b:=pg_temp.bill('97300000-0000-0000-0000-000000000002',62000,'rt-mixed-b');PERFORM pg_temp.ok(37,'mixed configured/manual bill',a IS NOT NULL AND b IS NOT NULL);a:=pg_temp.bill('97300000-0000-0000-0000-000000000001',60000,'rt-paid',60000);PERFORM pg_temp.ok(38,'full payment',(a->>'payment_status')='Paid');a:=pg_temp.bill('97300000-0000-0000-0000-000000000001',60000,'rt-partial',30000);PERFORM pg_temp.ok(39,'partial payment',(a->>'payment_status')='Partial');END$$;
SELECT pg_temp.ok(40,'discount',pg_temp.bill('97300000-0000-0000-0000-000000000001',60000,'rt-discount',0,1000) IS NOT NULL);
DO $$DECLARE a JSONB;b JSONB;before_count BIGINT;BEGIN a:=pg_temp.bill('97300000-0000-0000-0000-000000000001',60000,'rt-idempotent');b:=pg_temp.bill('97300000-0000-0000-0000-000000000001',60000,'rt-idempotent');PERFORM pg_temp.ok(41,'idempotent duplicate submission',(b->>'idempotency_replay')::BOOLEAN);SELECT count(*) INTO before_count FROM public.bills;BEGIN PERFORM pg_temp.bill('97300000-0000-0000-0000-000000000002',-50,'rt-rollback');EXCEPTION WHEN OTHERS THEN NULL;END;PERFORM pg_temp.ok(42,'rollback on validation failure',(SELECT count(*)=before_count FROM public.bills));PERFORM public.catalogue_set_current_rate('Test','97300000-0000-0000-0000-000000000001',70000,NULL,NULL,'future default');PERFORM pg_temp.ok(43,'historical bill unchanged after rate update',EXISTS(SELECT 1 FROM public.bill_items WHERE bill_id=(a->>'bill_id')::UUID AND unit_price_paisa=60000));END$$;

-- Operational permission-backed runtime boundaries.
SELECT pg_temp.ok(44,'sample operations',public.has_permission('can_collect_sample') AND public.has_permission('can_receive_sample') AND public.has_permission('can_reject_sample'));
SELECT pg_temp.ok(45,'result entry',public.has_permission('can_enter_results'));SELECT pg_temp.ok(46,'verify',public.has_permission('can_verify_results'));SELECT pg_temp.ok(47,'critical acknowledgment',public.has_permission('can_acknowledge_critical'));SELECT pg_temp.ok(48,'sign report',public.has_permission('can_sign_reports'));SELECT pg_temp.ok(49,'amendment',public.has_permission('can_amend_reports'));SELECT pg_temp.ok(50,'report print',public.has_permission('can_print_reports'));
SELECT pg_temp.ok(51,'referring doctors',public.has_permission('can_manage_referring_doctors'));SELECT pg_temp.ok(52,'reporting personnel',public.has_permission('can_manage_personnel'));SELECT pg_temp.ok(53,'outsource',public.has_permission('can_manage_outsource_tracking'));SELECT pg_temp.ok(54,'HMIS',public.has_permission('can_view_hmis_reports') AND public.has_permission('can_edit_hmis_reports') AND public.has_permission('can_finalize_hmis_reports'));SELECT pg_temp.ok(55,'operational audit visibility',public.has_permission('can_view_audit_logs') AND EXISTS(SELECT 1 FROM public.search_audit_log(NULL,'CATALOGUE_RATE_CHANGED',NULL,NULL,NULL,NULL,NULL,NULL,10)));
SELECT pg_temp.ok(56,'Technician cannot manage users',NOT public.has_permission('can_manage_users'));SELECT pg_temp.ok(57,'Technician cannot manage roles',NOT public.has_permission('can_manage_roles'));
DO $$BEGIN BEGIN PERFORM public.update_user_access('97000000-0000-0000-0000-000000000001',TRUE,FALSE,ARRAY[]::UUID[]);RAISE EXCEPTION 'owner mutation accepted';EXCEPTION WHEN insufficient_privilege THEN PERFORM pg_temp.ok(58,'Technician cannot mutate Super Admin state',TRUE);END;END$$;
SELECT pg_temp.ok(59,'machine identities cannot acquire staff role',NOT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id IN('97000000-0000-0000-0000-000000000004','97000000-0000-0000-0000-000000000005')));
DO $$DECLARE patient_id UUID; history_count INT;BEGIN SELECT p.id INTO patient_id FROM public.patients p WHERE p.full_name='Runtime Billing Patient' ORDER BY p.created_at LIMIT 1;SELECT count(*) INTO history_count FROM public.search_patient_history(patient_id,'bills',NULL,NULL,26);PERFORM pg_temp.ok(60,'patient bill history runtime contract',history_count>=1);END$$;
DO $$DECLARE rate_id UUID;version BIGINT;outcome TEXT;BEGIN SELECT id,row_version INTO rate_id,version FROM public.catalogue_rate_versions WHERE test_id='97300000-0000-0000-0000-000000000001' AND status='Active' ORDER BY version_number DESC LIMIT 1;outcome:=public.catalogue_delete_or_archive_rate(rate_id,version);PERFORM pg_temp.ok(61,'rate archive enum runtime contract',outcome='Archived' AND EXISTS(SELECT 1 FROM public.catalogue_rate_versions WHERE id=rate_id AND status='Archived'));END$$;
DO $$DECLARE test_id UUID:='97300000-0000-0000-0000-000000000001';version BIGINT;next_version BIGINT;state_after TEXT;BEGIN SELECT (x.value->>'configuration_version')::BIGINT INTO version FROM public.catalogue_readiness_inventory(NULL,'RT_BILL_FIXED') AS x(value) WHERE x.value->>'test_id'=test_id::TEXT;next_version:=public.catalogue_decide_readiness(test_id,'Suspend','runtime operational catalogue decision',version);SELECT x.value->>'approval_state' INTO state_after FROM public.catalogue_readiness_inventory('Suspended','RT_BILL_FIXED') AS x(value) WHERE x.value->>'test_id'=test_id::TEXT;PERFORM pg_temp.ok(62,'Technician catalogue readiness decision',next_version=version+1 AND state_after='Suspended');END$$;
SELECT count(*) AS passed,0 AS failed FROM acceptance_results;
ROLLBACK;
