import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const migration=fs.readFileSync(new URL('../supabase/migrations/00092_multi_report_group_lifecycle.sql',import.meta.url),'utf8');
const result=fs.readFileSync(new URL('../src/features/worklist/ResultEntryPage.tsx',import.meta.url),'utf8');
const billing=fs.readFileSync(new URL('../src/features/billing/NewBillPage.tsx',import.meta.url),'utf8');
const routes=fs.readFileSync(new URL('../src/app/routes.tsx',import.meta.url),'utf8');
const worker=fs.readFileSync(new URL('../cloudflare/report-artifacts/src/index.ts',import.meta.url),'utf8');
test('migration is forward-only 00092',()=>assert.match(migration,/Multi-investigation orders with frozen clinical report groups/));
test('catalogue stores stable report group configuration',()=>{for(const field of['report_group_key','report_group_title','report_section','report_group_sort_order'])assert.match(migration,new RegExp(field))});
test('group membership is frozen per order item',()=>{assert.match(migration,/clinical_report_group_items/);assert.match(migration,/frozen_test_code/);assert.match(migration,/order_item_id UUID NOT NULL UNIQUE/)});
test('legacy whole-order reports remain nullable and independently unique',()=>{assert.match(migration,/report_group_id IS NULL/);assert.match(migration,/uq_diagnostic_reports_group_version/)});
test('readiness is group-scoped',()=>assert.match(migration,/check_report_group_readiness\(p_report_group_id UUID\)/));
test('signing updates group members rather than every order item',()=>{assert.match(migration,/sign_report_group/);assert.match(migration,/gi\.report_group_id=g\.id AND gi\.order_item_id=oi\.id/)});
test('snapshots carry group identity',()=>assert.match(migration,/'report_group',jsonb_build_object/));
test('order status is derived and supports partial reporting',()=>{assert.match(migration,/Partially Reported/);assert.match(migration,/Fully Reported/)});
test('first PDF milestone has order-aware SMS identity',()=>assert.match(migration,/'ORDER_REPORT_READY:'\|\|report\.order_id\|\|':1'/));
test('later automatic milestones are skipped',()=>assert.match(migration,/Order already notified/));
test('explicit updated-report notification is generation and concurrency guarded',()=>{assert.match(migration,/notify_updated_order_reports/);assert.match(migration,/p_expected_generation/);assert.match(migration,/ORDER_REPORT_READY:'\|\|p_order_id\|\|':'\|\|next_generation/)});
test('order entitlement cannot expose arbitrary patient history',()=>{assert.match(migration,/order_report_delivery_entitlements/);assert.match(migration,/r\.report_group_id=e\.report_group_id/)});
test('legacy direct PDF routes remain supported',()=>{assert.match(worker,/\/api\/reports\//);assert.match(worker,/\/r\//)});
test('new patient portal never exposes draft values',()=>{assert.match(worker,/Final report ready/);assert.match(worker,/no draft results are shown/);assert.doesNotMatch(worker,/clinical_snapshot_json/)});
test('result entry has order-centric route and group sign action',()=>{assert.match(routes,/worklist\/order\/:orderId/);assert.match(result,/sign_and_queue_report_group/);assert.match(result,/Sign \$\{reportGroup/)});
test('mixed panel billing preserves explicit panel snapshot path',()=>{assert.doesNotMatch(billing,/Book a panel service on its own bill/);assert.match(billing,/create_patient_bill_order_mixed_catalogue/);assert.match(migration,/bill_panel_selections/)});
