\set ON_ERROR_STOP on
BEGIN;
CREATE TEMP TABLE outsource_results(n int primary key,name text); GRANT ALL ON outsource_results TO authenticated,anon,service_role;
CREATE OR REPLACE FUNCTION pg_temp.ok(n int,name text,condition boolean) RETURNS void LANGUAGE plpgsql AS $$BEGIN IF NOT coalesce(condition,false) THEN RAISE EXCEPTION 'TEST_%_FAILED: %',n,name; END IF; INSERT INTO outsource_results VALUES(n,name); RAISE NOTICE 'PASS %: %',n,name; END$$;
GRANT EXECUTE ON FUNCTION pg_temp.ok(int,text,boolean) TO authenticated,anon,service_role;
INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES('99400000-0000-0000-0000-000000000001','outsource-tech@example.invalid','{"full_name":"Outsource Runtime Technician"}') ON CONFLICT DO NOTHING;
INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES('99400000-0000-0000-0000-000000000002','outsource-inactive@example.invalid','{}'),('99400000-0000-0000-0000-000000000003','outsource-gateway@example.invalid','{}'),('99400000-0000-0000-0000-000000000004','outsource-worker@example.invalid','{}') ON CONFLICT DO NOTHING;
UPDATE public.user_profiles SET is_active=true,is_super_admin=false WHERE id='99400000-0000-0000-0000-000000000001'; INSERT INTO public.user_roles(user_id,role_id) SELECT '99400000-0000-0000-0000-000000000001',id FROM public.roles WHERE name='Lab Technician' ON CONFLICT DO NOTHING;
SET LOCAL ROLE authenticated; SELECT set_config('request.jwt.claim.sub','99400000-0000-0000-0000-000000000001',true);
SELECT public.configure_reference_laboratory('{"code":"REF_A","name":"Synthetic Reference Laboratory A","external_code":"A"}',NULL); SELECT public.configure_reference_laboratory('{"code":"REF_B","name":"Synthetic Reference Laboratory B","external_code":"B"}',NULL);
DO $$DECLARE items jsonb[]; response jsonb; oid uuid; t record; BEGIN
 FOR t IN SELECT * FROM public.tests WHERE code=ANY(ARRAY['CBC','LFT','HCV_RNA_QUANTITATIVE','IHC']) ORDER BY code LOOP items:=array_append(items,jsonb_build_object('test_id',t.id,'unit_price_paisa',CASE WHEN t.price_paisa>0 THEN t.price_paisa ELSE 10000 END,'manual_price_paisa',CASE WHEN t.price_paisa>0 THEN t.price_paisa ELSE 10000 END,'discount_paisa',0,'zero_price_acknowledged',false)); END LOOP;
 response:=public.create_patient_bill_order_with_packages('{"mobile":"9800000292","full_name":"Synthetic Outsource Patient","gender":"Female","age_years":40,"address":"Synthetic"}',jsonb_build_object('discount_amount_paisa',0,'paid_amount_paisa',0,'order_date_bs','2083-05-15','remarks','rollback outsource runtime'),items,NULL,'outsource-00092','[]'); oid:=(response->>'order_id')::uuid; PERFORM set_config('out.order',oid::text,true);
 PERFORM pg_temp.ok(1,'mixed internal and outsource routes frozen',2=(SELECT count(*) FROM public.clinical_order_items WHERE order_id=oid AND execution_route='INTERNAL') AND 2=(SELECT count(*) FROM public.clinical_order_items WHERE order_id=oid AND execution_route='OUTSOURCE'));
 PERFORM pg_temp.ok(2,'route frozen in report membership',2=(SELECT count(*) FROM public.clinical_report_group_items gi JOIN public.clinical_report_groups g ON g.id=gi.report_group_id WHERE g.order_id=oid AND gi.execution_route='OUTSOURCE'));
 PERFORM pg_temp.ok(3,'outsource trackers linked per order item',2=(SELECT count(*) FROM public.outsource_samples WHERE order_item_id IN(SELECT id FROM public.clinical_order_items WHERE order_id=oid AND execution_route='OUTSOURCE')));
END$$;
RESET ROLE; UPDATE public.samples SET status='Received',collected_at=now(),received_at=now(),collected_by='99400000-0000-0000-0000-000000000001',collected_by_name='Outsource Runtime Technician',received_by='99400000-0000-0000-0000-000000000001',received_by_name='Outsource Runtime Technician' WHERE order_id=current_setting('out.order')::uuid; UPDATE public.test_results SET display_value='1',numeric_value=1,status='Verified' WHERE order_item_id IN(SELECT id FROM public.clinical_order_items WHERE order_id=current_setting('out.order')::uuid AND execution_route='INTERNAL'); UPDATE public.clinical_order_items SET status='Verified' WHERE order_id=current_setting('out.order')::uuid AND execution_route='INTERNAL';
SET LOCAL ROLE authenticated; SELECT set_config('request.jwt.claim.sub','99400000-0000-0000-0000-000000000001',true);
SELECT pg_temp.ok(4,'internal groups ready despite outsource delay',2=(SELECT count(*) FROM public.clinical_report_groups g WHERE g.order_id=current_setting('out.order')::uuid AND g.group_key IN('hematology','biochemistry') AND (public.check_report_group_readiness(g.id)->>'is_ready')::boolean));
SELECT pg_temp.ok(5,'outsource groups blocked before receipt',2=(SELECT count(*) FROM public.clinical_report_groups g WHERE g.order_id=current_setting('out.order')::uuid AND g.group_key IN('molecular_outsource','anatomic_pathology') AND NOT (public.check_report_group_readiness(g.id)->>'is_ready')::boolean));
DO $$DECLARE oi record; lab uuid; payload jsonb; BEGIN
 FOR oi IN SELECT x.id,t.code FROM public.clinical_order_items x JOIN public.tests t ON t.id=x.test_id WHERE x.order_id=current_setting('out.order')::uuid AND x.execution_route='OUTSOURCE' LOOP
  SELECT id INTO lab FROM public.reference_laboratories WHERE code=CASE WHEN oi.code='HCV_RNA_QUANTITATIVE' THEN 'REF_A' ELSE 'REF_B' END;
  PERFORM public.transition_outsource_order_item(oi.id,'Dispatched',lab,'SYNTHETIC-'||oi.code,'{}','Synthetic dispatch'); PERFORM public.transition_outsource_order_item(oi.id,'AwaitingExternalResult',NULL,NULL,'{}','Received by reference laboratory');
  SELECT jsonb_build_object('result_type',CASE WHEN oi.code='IHC' THEN 'NARRATIVE' ELSE 'NUMERIC' END,'source_report_reference','SYNTHETIC-SOURCE-'||oi.code,'method','External governed assay','interpretation','Synthetic clinical interpretation','results',jsonb_agg(jsonb_build_object('parameter_code',p.code,'display_value',CASE WHEN p.value_type='Numeric' THEN '1' ELSE 'Synthetic external result' END,'numeric_value',CASE WHEN p.value_type='Numeric' THEN '1' ELSE NULL END,'text_value',CASE WHEN p.value_type='Numeric' THEN NULL ELSE 'Synthetic external result' END))) INTO payload FROM public.parameters p JOIN public.tests t ON t.id=p.test_id WHERE t.code=oi.code AND p.is_active AND p.value_type<>'Heading';
  PERFORM public.transition_outsource_order_item(oi.id,'ResultReceived',NULL,NULL,payload,'External report received'); PERFORM public.transition_outsource_order_item(oi.id,'InternalReview',NULL,NULL,'{}','Reviewed against source report'); PERFORM public.transition_outsource_order_item(oi.id,'Verified',NULL,NULL,'{}','Verified internally');
 END LOOP;
END$$;
SELECT pg_temp.ok(6,'quantitative and narrative outsource results captured',2=(SELECT count(*) FROM public.clinical_order_items WHERE order_id=current_setting('out.order')::uuid AND outsource_state='Verified' AND outsource_result_payload IS NOT NULL));
SELECT pg_temp.ok(7,'multiple reference laboratories remain independent',2=(SELECT count(DISTINCT reference_laboratory_id) FROM public.clinical_order_items WHERE order_id=current_setting('out.order')::uuid AND execution_route='OUTSOURCE'));
SELECT pg_temp.ok(8,'outsource provenance is audit recorded',10<=(SELECT count(*) FROM public.audit_logs WHERE entity_type='ClinicalOrderItem' AND entity_id IN(SELECT id::text FROM public.clinical_order_items WHERE order_id=current_setting('out.order')::uuid AND execution_route='OUTSOURCE')));
SELECT pg_temp.ok(9,'outsource groups ready only after internal review and verification',2=(SELECT count(*) FROM public.clinical_report_groups g WHERE g.order_id=current_setting('out.order')::uuid AND g.group_key IN('molecular_outsource','anatomic_pathology') AND (public.check_report_group_readiness(g.id)->>'is_ready')::boolean));
SELECT pg_temp.ok(10,'external evidence populated governed result rows',NOT EXISTS(SELECT 1 FROM public.test_results tr JOIN public.clinical_order_items oi ON oi.id=tr.order_item_id JOIN public.parameters p ON p.id=tr.parameter_id WHERE oi.order_id=current_setting('out.order')::uuid AND oi.execution_route='OUTSOURCE' AND p.is_mandatory AND nullif(btrim(tr.display_value),'') IS NULL));

-- Independent rejection/recollection lineage.
DO $$DECLARE item jsonb[]; response jsonb; oi uuid; lab uuid; t record; BEGIN SELECT * INTO t FROM public.tests WHERE code='IHC'; item:=ARRAY[jsonb_build_object('test_id',t.id,'unit_price_paisa',CASE WHEN t.price_paisa>0 THEN t.price_paisa ELSE 10000 END,'manual_price_paisa',CASE WHEN t.price_paisa>0 THEN t.price_paisa ELSE 10000 END,'discount_paisa',0,'zero_price_acknowledged',false)]; response:=public.create_patient_bill_order_with_packages('{"mobile":"9800000392","full_name":"Synthetic Recollection Patient","gender":"Other","age_years":50,"address":"Synthetic"}','{"discount_amount_paisa":0,"paid_amount_paisa":0,"order_date_bs":"2083-05-15"}',item,NULL,'outsource-recollect-00092','[]'); SELECT id INTO oi FROM public.clinical_order_items WHERE order_id=(response->>'order_id')::uuid; SELECT id INTO lab FROM public.reference_laboratories WHERE code='REF_B'; PERFORM public.transition_outsource_order_item(oi,'Dispatched',lab,'REJECT-ME','{}','Synthetic dispatch'); PERFORM public.transition_outsource_order_item(oi,'RecollectionRequired',NULL,NULL,'{}','Reference laboratory rejected specimen'); PERFORM set_config('out.recollect_item',oi::text,true); END$$;
RESET ROLE;
SELECT pg_temp.ok(11,'rejection preserves original and creates recollection lineage',2=(SELECT count(*) FROM public.outsource_samples WHERE order_item_id=current_setting('out.recollect_item')::uuid) AND 1=(SELECT count(*) FROM public.outsource_samples WHERE order_item_id=current_setting('out.recollect_item')::uuid AND status='Rejected') AND 1=(SELECT count(*) FROM public.outsource_samples WHERE order_item_id=current_setting('out.recollect_item')::uuid AND recollects_outsource_sample_id IS NOT NULL));
SELECT pg_temp.ok(12,'recollection creates no false clinical output',NOT EXISTS(SELECT 1 FROM public.diagnostic_reports r JOIN public.clinical_report_groups g ON g.id=r.report_group_id JOIN public.clinical_report_group_items gi ON gi.report_group_id=g.id WHERE gi.order_item_id=current_setting('out.recollect_item')::uuid));

-- Returning patient: same mobile/UHID, new bill/order/sample context.
SET LOCAL ROLE authenticated; SELECT set_config('request.jwt.claim.sub','99400000-0000-0000-0000-000000000001',true);
DO $$DECLARE t record; item jsonb[]; a jsonb; b jsonb; BEGIN SELECT * INTO t FROM public.tests WHERE code='CBC'; item:=ARRAY[jsonb_build_object('test_id',t.id,'unit_price_paisa',t.price_paisa,'manual_price_paisa',t.price_paisa,'discount_paisa',0,'zero_price_acknowledged',false)]; a:=public.create_patient_bill_order_with_packages('{"mobile":"9800000492","full_name":"Synthetic Returning Patient","gender":"Male","age_years":32,"address":"Synthetic"}','{"discount_amount_paisa":0,"paid_amount_paisa":0,"order_date_bs":"2083-05-15"}',item,NULL,'return-visit-1','[]'); SELECT * INTO t FROM public.tests WHERE code='CREATININE'; item:=ARRAY[jsonb_build_object('test_id',t.id,'unit_price_paisa',CASE WHEN t.price_paisa>0 THEN t.price_paisa ELSE 10000 END,'manual_price_paisa',CASE WHEN t.price_paisa>0 THEN t.price_paisa ELSE 10000 END,'discount_paisa',0,'zero_price_acknowledged',false)]; b:=public.create_patient_bill_order_with_packages('{"mobile":"9800000492","full_name":"Synthetic Returning Patient","gender":"Male","age_years":32,"address":"Synthetic"}','{"discount_amount_paisa":0,"paid_amount_paisa":0,"order_date_bs":"2083-05-16"}',item,NULL,'return-visit-2','[]'); PERFORM set_config('return.patient',a->>'patient_id',true); END$$;
RESET ROLE;
SELECT pg_temp.ok(13,'returning patient reuses one identity and UHID',1=(SELECT count(*) FROM public.patients WHERE mobile='9800000492') AND 2=(SELECT count(*) FROM public.bills WHERE patient_id=current_setting('return.patient')::uuid) AND 2=(SELECT count(*) FROM public.clinical_orders WHERE patient_id=current_setting('return.patient')::uuid));
SET LOCAL ROLE authenticated;
DO $$DECLARE uid uuid; BEGIN FOREACH uid IN ARRAY ARRAY['99400000-0000-0000-0000-000000000002'::uuid,'99400000-0000-0000-0000-000000000003'::uuid,'99400000-0000-0000-0000-000000000004'::uuid] LOOP PERFORM set_config('request.jwt.claim.sub',uid::text,true); BEGIN PERFORM public.transition_outsource_order_item(current_setting('out.recollect_item')::uuid,'Dispatched',NULL,NULL,'{}','denied'); RAISE EXCEPTION 'machine/inactive identity accepted'; EXCEPTION WHEN insufficient_privilege THEN NULL; END; END LOOP; PERFORM pg_temp.ok(14,'inactive and machine identities denied',true); END$$;
RESET ROLE; SET LOCAL ROLE anon; DO $$BEGIN BEGIN PERFORM public.transition_outsource_order_item(current_setting('out.recollect_item')::uuid,'Dispatched',NULL,NULL,'{}','denied'); RAISE EXCEPTION 'anon accepted'; EXCEPTION WHEN insufficient_privilege THEN PERFORM pg_temp.ok(15,'anonymous denied',true); END; END$$;
RESET ROLE; SET LOCAL ROLE service_role; DO $$BEGIN BEGIN PERFORM public.transition_outsource_order_item(current_setting('out.recollect_item')::uuid,'Dispatched',NULL,NULL,'{}','denied'); RAISE EXCEPTION 'service role accepted'; EXCEPTION WHEN insufficient_privilege THEN PERFORM pg_temp.ok(16,'service role denied',true); END; END$$;
RESET ROLE; SET LOCAL ROLE authenticated; SELECT set_config('request.jwt.claim.sub','99400000-0000-0000-0000-000000000001',true); DO $$BEGIN BEGIN UPDATE public.clinical_order_items SET outsource_state='Signed' WHERE id=current_setting('out.recollect_item')::uuid; RAISE EXCEPTION 'direct mutation accepted'; EXCEPTION WHEN insufficient_privilege THEN PERFORM pg_temp.ok(17,'direct order-item mutation denied',true); END; END$$;
RESET ROLE;
SELECT count(*) passed,0 failed FROM outsource_results;
ROLLBACK;
