import fs from 'node:fs'; import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(p,'utf8'); const migration=read('supabase/migrations/00033_hmis_monthly_reporting.sql'); const finalAuthorization=read('supabase/migrations/00087_production_catalogue_rate_management.sql'); const page=read('src/features/hmis/HmisMonthlyReportPage.tsx'); const model=read('src/features/hmis/hmisModel.ts'); const printing=read('src/features/hmis/hmisPrint.ts'); const routes=read('src/app/routes.tsx'); const permissions=read('src/types/permissions.ts'); let pass=0;
const check=(name,fn)=>{fn();pass++;console.log(`PASS HMIS: ${name}`)};
check('pending migration uses production-safe UUID defaults',()=>{assert.equal(migration.includes('uuid_generate_v4()'),false);assert.equal((migration.match(/DEFAULT gen_random_uuid\(\)/g)||[]).length,4)});
check('digest remains schema qualified',()=>assert.ok(migration.includes("extensions.digest(convert_to(p_snapshot::text,'UTF8'),'sha256')")));
check('aggregate security definer enforces view permission',()=>assert.ok(migration.includes("FROM metrics,ages WHERE public.has_permission('can_view_hmis_reports')")));
check('snapshot rejects patient-detail keys',()=>assert.ok(migration.includes('Patient-identifiable or clinical-detail keys are forbidden')));
check('nine age bands',()=>assert.equal((model.match(/'[^']*Year[s]?'/g)||[]).length>=9,true));
for(const label of ['<1 Year','1–4 Years','5–9 Years','10–14 Years','15–19 Years','20–29 Years','30–59 Years','60–69 Years','70+ Years'])check(`age band ${label}`,()=>assert.ok(model.includes(label)));
check('Nepal month boundaries used',()=>assert.ok(page.includes('getNepalMonthBoundsFromKey')));
check('zero activity coalesced',()=>assert.ok(migration.includes("COALESCE(jsonb_object_agg")));
check('auto source aggregation',()=>assert.ok(migration.includes('hmis_auto_summary')));
check('manual values separated',()=>assert.ok(migration.includes('hmis_monthly_manual_values')));
check('facility config',()=>assert.ok(migration.includes('hmis_facility_configuration')));
check('explicit service availability',()=>assert.ok(model.includes("'Available' | 'Not Available' | 'Not Applicable'")));
check('finalized snapshot versions',()=>assert.ok(migration.includes('hmis_monthly_report_versions')));
check('SHA-256',()=>assert.ok(migration.includes("'sha256'")));
check('immutability trigger',()=>assert.ok(migration.includes('hmis_versions_immutable')));
check('revision reason',()=>assert.ok(migration.includes('Revision reason required')));
check('revision parent linkage',()=>assert.ok(migration.includes('parent_version')&&migration.includes('hmis_version_parent_fk')));
check('explicit identity options',()=>assert.ok(migration.includes('hmis_identity_options')&&model.includes("'ReportingPersonnel'|'Staff'")));
check('prepared identity required',()=>assert.ok(migration.includes('Prepared By must be selected explicitly')));
check('identity snapshots frozen',()=>assert.ok(model.includes('HmisIdentitySnapshot')&&page.includes('identities:{prepared')));
check('roles never auto-copied',()=>assert.ok(page.includes('never copied between roles')));
check('total clients manual provenance',()=>assert.ok(page.includes('Total Clients Served and emergency: Manual HMIS Entry')));
check('submission tracking',()=>assert.ok(migration.includes('hmis_submission_events')));
check('private optional attachment path',()=>assert.ok(migration.includes('attachment_path')));
for(const key of ['can_view_hmis_reports','can_edit_hmis_reports','can_finalize_hmis_reports'])check(`RBAC ${key}`,()=>assert.ok(migration.includes(key)&&permissions.includes(key.toUpperCase())));
check('technician granted operational HMIS finalization',()=>assert.match(finalAuthorization,/can_finalize_hmis_reports/));
check('RLS all HMIS tables',()=>assert.equal((migration.match(/ENABLE ROW LEVEL SECURITY/g)||[]).length,5));
check('A4 landscape',()=>assert.ok(printing.includes('A4 landscape')));
check('repeat table headers',()=>assert.ok(printing.includes('table-header-group')));
check('isolated iframe print',()=>assert.ok(printing.includes("createElement('iframe')")));
check('no clinical watermark or QR',()=>assert.equal(/watermark|qrCode|clinical report/i.test(printing),false));
check('CSV summary has no PII fields',()=>assert.equal(/mobile|patientName|uhid/i.test(model.match(/export function csvSummary[\s\S]+/)?.[0]||''),false));
check('administration route',()=>assert.ok(routes.includes("path: 'admin/hmis'")));
check('disease not inferred from tests',()=>assert.ok(page.includes('never inferred from test names')));
check('signatures not fabricated',()=>assert.ok(page.includes("'Not provided'")));
check('clinical schema untouched',()=>assert.equal(/ALTER TABLE public\.(patients|bills|clinical_orders|diagnostic_reports)/.test(migration),false));
console.log(`HMIS SUITE: ${pass} PASS / 0 FAIL`);
